// Generated by tools/gen_travel.py. Do not edit by hand.
// Include only from the world map and the flight scene: it pulls in both continent pictures.
#ifndef GW_CONTINENTS_H
#define GW_CONTINENTS_H

#include "bn_sprite_items_continent_eastern.h"
#include "bn_sprite_items_continent_kalimdor.h"

#include "gw_ids.h"

namespace gw
{

// A 128x128 picture of a continent in four 64x64 frames.
struct continent_def
{
    const char* name;
    const bn::sprite_item& item;
};

constexpr continent_def continents[] = {
    { "Eastern Kingdoms", bn::sprite_items::continent_eastern },
    { "Kalimdor", bn::sprite_items::continent_kalimdor },
};

constexpr int continent_count = sizeof(continents) / sizeof(continents[0]);

// The zones of the route, in continent order. map is NONE until the zone is in the game.
enum class zone_id : uint8_t
{
    TIRISFAL_GLADES,
    WESTERN_PLAGUELANDS,
    EASTERN_PLAGUELANDS,
    SILVERPINE_FOREST,
    HILLSBRAD_FOOTHILLS,
    WETLANDS,
    IRONFORGE,
    BADLANDS,
    BURNING_STEPPES,
    ELWYNN_FOREST,
    STORMWIND_CITY,
    REDRIDGE_MOUNTAINS,
    WESTFALL,
    DUSKWOOD,
    SWAMP_OF_SORROWS,
    STRANGLETHORN_VALE,
    DARKSHORE,
    ASHENVALE,
    DESOLACE,
    FERALAS,
    THOUSAND_NEEDLES,
    TANARIS,
    COUNT
};

struct zone_def
{
    const char* name;
    uint8_t continent;
    uint8_t x;              // its spot on the continent picture
    uint8_t y;
    uint8_t min_level;
    uint8_t max_level;
    map_id map;
};

constexpr zone_def zones[] = {
    { "Tirisfal Glades", 0, 36, 23, 1, 10, map_id::NONE },
    { "Western Plaguelands", 0, 56, 26, 55, 60, map_id::NONE },
    { "Eastern Plaguelands", 0, 80, 26, 55, 60, map_id::NONE },
    { "Silverpine Forest", 0, 31, 38, 20, 25, map_id::NONE },
    { "Hillsbrad Foothills", 0, 52, 42, 30, 35, map_id::NONE },
    { "Wetlands", 0, 59, 57, 25, 30, map_id::NONE },
    { "Ironforge", 0, 47, 71, 25, 30, map_id::NONE },
    { "Badlands", 0, 68, 81, 50, 55, map_id::NONE },
    { "Burning Steppes", 0, 57, 87, 50, 55, map_id::NONE },
    { "Elwynn Forest", 0, 45, 96, 1, 10, map_id::ELWYNN },
    { "Stormwind City", 0, 37, 91, 1, 60, map_id::STORMWIND },
    { "Redridge Mountains", 0, 63, 96, 15, 20, map_id::REDRIDGE },
    { "Westfall", 0, 33, 104, 10, 15, map_id::WESTFALL },
    { "Duskwood", 0, 49, 105, 20, 25, map_id::NONE },
    { "Swamp of Sorrows", 0, 69, 107, 50, 55, map_id::NONE },
    { "Stranglethorn Vale", 0, 42, 113, 35, 40, map_id::NONE },
    { "Darkshore", 1, 46, 31, 10, 20, map_id::NONE },
    { "Ashenvale", 1, 60, 39, 20, 30, map_id::NONE },
    { "Desolace", 1, 41, 57, 45, 50, map_id::NONE },
    { "Feralas", 1, 40, 76, 45, 50, map_id::NONE },
    { "Thousand Needles", 1, 64, 82, 40, 45, map_id::NONE },
    { "Tanaris", 1, 69, 99, 40, 45, map_id::NONE },
};

static_assert(sizeof(zones) / sizeof(zones[0]) == int(zone_id::COUNT));

}

#endif
