#ifndef GW_IDS_H
#define GW_IDS_H

#include <cstdint>

// Identifiers shared by the generated map headers (tools/gen_world.py) and the game data.
// Keep the names in sync with the generator. Saves store map ids by value: only append. The world
// will need more than 255 maps, npcs and enemy types, so those ids are 16 bits wide.

namespace gw
{

enum class race_id : uint8_t
{
    HUMAN,
    DWARF,
    NIGHT_ELF,
    COUNT
};

enum class class_id : uint8_t
{
    WARRIOR,
    MAGE,
    HUNTER,
    COUNT
};

// Three per class, in the order of the class's talent trees. Saves store these values; NONE is a
// character from before subclasses, who picks one when the save loads.
enum class subclass_id : uint8_t
{
    NONE,
    ARMS,
    FURY,
    PROTECTION,
    ARCANE,
    FIRE,
    FROST,
    BEAST_MASTERY,
    MARKSMANSHIP,
    SURVIVAL,
    COUNT
};

constexpr int subclasses_per_class = 3;

[[nodiscard]] constexpr class_id subclass_class(subclass_id subclass)
{
    return class_id((int(subclass) - 1) / subclasses_per_class);
}

// The subclass's place among its class's three, which is also its talent tree.
[[nodiscard]] constexpr int subclass_index(subclass_id subclass)
{
    return (int(subclass) - 1) % subclasses_per_class;
}

[[nodiscard]] constexpr subclass_id class_subclass(class_id player_class, int index)
{
    return subclass_id(1 + int(player_class) * subclasses_per_class + index);
}

enum class map_id : uint16_t
{
    NONE,
    ELWYNN,
    ABBEY,
    INN,
    WESTFALL,
    DEADMINES,
    ECHO_RIDGE,
    FARGODEEP,
    STORMWIND,
    STOCKADE,
    DEEPRUN_TRAM,
    REDRIDGE,
    DUSKWOOD,
    SILVERPINE,
    SHADOWFANG,
    IRONFORGE,
    DUN_MOROGH,
    WETLANDS,
    DARKSHORE,
    BLACKFATHOM_DEEPS,
    GNOMEREGAN,
    HILLSBRAD,
    TIRISFAL,
    SM_GRAVEYARD,
    SM_LIBRARY,
    STRANGLETHORN,
    SM_ARMORY,
    SM_CATHEDRAL,
    TANARIS,
    THOUSAND_NEEDLES,
    RAZORFEN_KRAUL,
    RAZORFEN_DOWNS,
    ZUL_FARRAK,
    COUNT
};

enum class music_id : uint8_t
{
    NONE,
    TITLE,
    ELWYNN,
    TOWN,
    WESTFALL,
    DUNGEON,
    BOSS,
    REDRIDGE,
    DUSKWOOD,
    IRONFORGE,
    WETLANDS,
    HILLSBRAD,
    MONASTERY,
    STRANGLETHORN,
    TANARIS
};

enum class area_id : uint8_t
{
    NONE,
    FARGODEEP,
    IRONCLAD_COVE,
    ECHO_RIDGE,
    MOONBROOK,
    LAKE_EVERSTILL,     // fishing waters
    MISTMANTLE_MANOR,
    THANDOL_SPAN,
    RADIATION,          // fallout that burns whoever stands in it; unnamed, under a named room
    THE_STACKS,
    GONG,               // where A rings a gong that starts an event (combat::start_event); unnamed
    CAGE                // the same for a cage whose lock is broken
};

enum class npc_id : uint16_t
{
    NONE,
    WILLEM,
    MCBRIDE,
    LLANE,
    DANIL,
    GUARD_NS,
    DUGHAN,
    LYRIA,
    CORINA,
    FARLEY,
    REMY,
    GUARD_GS,
    GUARD_WEST,
    MA_STONEFIELD,
    GRYAN,
    SALMA,
    GUARD_WF,
    KHELDEN,
    THORGAS,
    EAGAN,
    MILLY,
    ANDREW,
    FURLBROW,
    LEWIS,
    HEATHER,
    MARCUS_JONATHAN,
    SW_GUARD_GATE,
    SW_GUARD_KEEP,
    SW_GUARD_TRADE,
    BOLVAR,
    BENEDICTUS,
    ALLISON,
    GUNTHER,
    LINA,
    THURMAN,
    JENNEA,
    EINRIS,
    BRANN,
    ANDER,
    THELWATER,
    SW_GUARD_STOCKADE,
    DUNGAR,
    THOR,
    RANDAL,
    MONTY,
    // Redridge
    SOLOMON,
    MARRIS,
    OSLOW,
    BAREN,
    BREANNA,
    BRIANNA,
    OSGOOD,
    BRAY,
    BERTON,
    ARIENA,
    KAREN,
    GUARD_LAKERIDGE,
    // Duskwood
    ELLO,
    ALTHEA,
    EVA,
    SIRRA,
    CALOR,
    TRELAYNE,
    FELICIA,
    NIGHT_WATCH_GATE,
    NIGHT_WATCH_SQUARE,
    DARKSHIRE_VENDOR,
    SVEN,
    ABERCROMBIE,
    // Silverpine Forest
    VALDAN,
    GRYPHON_SILVERPINE,
    // Ironforge
    MAGNI,
    IRONFORGE_GUARD_SEAT,
    GERRIG,
    IRONFORGE_GUARD_GATE,
    GRYTH,
    FIREBREW,
    IRONFORGE_VENDOR,
    IRONFORGE_SMITH,
    MEKKATORQUE,
    SHONI,
    KELSTRUM,
    OLMIN,
    JULI,
    // Dun Morogh
    IRONFORGE_GUARD_OUTSIDE,
    OZZIE,
    MOUNTAINEER,
    // Wetlands
    STOUTFIST,
    HELBREK,
    MENETHIL_VENDOR,
    SHELLEI,
    HALLORAN,
    HARBORMASTER,
    MENETHIL_GUARD,
    WHELGAR,
    ORMER,
    // Darkshore
    SHAUSSIY,
    SHAEDLASS,
    CAYLAIS,
    SENTINEL,
    // Blackfathom Deeps
    THAELRID,
    // Hillsbrad Foothills
    MALEB,
    REDPATH,
    RALEIGH,
    DIBBS,
    DARREN_MALVEW,
    ANDERSON,
    SOUTHSHORE_VENDOR,
    SOUTHSHORE_SMITH,
    DARLA,
    SOUTHSHORE_GUARD,
    // Tirisfal Glades
    ARGENT_SCOUT,
    GRYPHON_TIRISFAL,
    // Stranglethorn Vale
    DOREN,
    BLUTH,
    REBEL_SOLDIER,
    HEMET,
    AJECK,
    ERLGADIN,
    BARNIL,
    REVILGAZ,
    SEAHORN,
    KEBOK,
    SKINDLE,
    GYLL,
    BRUISER,
    BOOTY_BAY_VENDOR,
    BOOTY_BAY_SMITH,
    // Tanaris and Thousand Needles
    BILGEWHIZZLE,
    FIZZGRIMBLE,
    BLIZRIK,
    KRINKLE,
    TRENTON,
    FIZZLEDOWSER,
    TRANREK,
    BERA,
    GADGETZAN_BRUISER,
    STOLEY,
    POZZIK,
    KRAVEL,
    FIZZLE_BRASSBOLTS,
    WIZZLE_BRASSBOLTS,
    ARGENT_GUARD_DALEN,
    COUNT
};

enum class enemy_id : uint16_t
{
    NONE,
    YOUNG_WOLF,
    KOBOLD_VERMIN,
    DEFIAS_THUG,
    TIMBER_WOLF,
    FOREST_SPIDER,
    KOBOLD_TUNNELER,
    MURLOC,
    BOAR,
    PRINCESS,
    RIVERPAW_GNOLL,
    HOGGER,
    HARVEST_WATCHER,
    DEFIAS_TRAPPER,
    DEFIAS_SMUGGLER,
    GNOLL_BRUTE,
    DEFIAS_MINER,
    GOBLIN_ENGINEER,
    SNEED,
    DEFIAS_PIRATE,
    VANCLEEF,
    DEFIAS_BLACKGUARD,
    DEFIAS_PRISONER,
    DEFIAS_CONVICT,
    DEFIAS_INSURGENT,
    TARGORR,
    KAM_DEEPFURY,
    BAZIL_THREDD,
    DEFIAS_RIOTER,
    // Redridge
    REDRIDGE_MONGREL,
    SHADOWHIDE_GNOLL,
    SHADOWHIDE_MYSTIC,
    RIBCHASER,
    MURLOC_FLESHEATER,
    GREAT_GORETUSK,
    BELLYGRUB,
    TARANTULA,
    BLACKROCK_OUTRUNNER,
    BLACKROCK_GRUNT,
    BLACKROCK_SHADOWCASTER,
    BLACKROCK_RENEGADE,
    BLACKROCK_SUMMONER,
    GATH_ILZOGG,
    // Duskwood
    DIRE_WOLF,
    RABID_DIRE_WOLF,
    VENOM_WEB_SPIDER,
    NIGHTBANE_DARK_RUNNER,
    NIGHTBANE_SHADOW_WEAVER,
    NIGHTBANE_TAINTED_ONE,
    SKELETAL_WARRIOR,
    SKELETAL_MAGE,
    SKELETAL_SERVANT,
    ROTTING_GHOUL,
    PLAGUE_SPREADER,
    SPLINTER_FIST_OGRE,
    SPLINTER_FIST_TASKMASTER,
    MOR_LADIM,
    STALVAN_MISTMANTLE,
    MORBENT_FEL,
    STITCHES,
    // Silverpine Forest and Shadowfang Keep
    BLEAK_WORG,
    SHADOWFANG_MOONWALKER,
    SHADOWFANG_DARKCASTER,
    SHADOWFANG_WOLFGUARD,
    HAUNTED_SERVITOR,
    WAILING_GUARDSMAN,
    RETHILGORE,
    RAZORCLAW_THE_BUTCHER,
    BARON_SILVERLAINE,
    COMMANDER_SPRINGVALE,
    ODO_THE_BLINDWATCHER,
    ARUGAL,
    LUPINE_HORROR,
    // Wetlands
    YOUNG_CROCOLISK,
    GIANT_CROCOLISK,
    MOTTLED_RAPTOR,
    MOTTLED_SCREECHER,
    SARLTOOTH,
    MOSSHIDE_GNOLL,
    MOSSHIDE_MYSTIC,
    BLUEGILL_MURLOC,
    DARK_IRON_DWARF,
    DARK_IRON_SABOTEUR,
    BALGARAS_THE_FOUL,
    DRAGONMAW_GRUNT,
    DRAGONMAW_SHADOWWARDER,
    NEK_ROSH,
    // Blackfathom Deeps
    BLACKFATHOM_MYRMIDON,
    BLACKFATHOM_TIDE_PRIESTESS,
    AKU_MAI_SNAPJAW,
    BLINDLIGHT_MURLOC,
    TWILIGHT_ACOLYTE,
    TWILIGHT_REAVER,
    AKU_MAI_SERVANT,
    GHAMOO_RA,
    LADY_SAREVESS,
    GELIHAST,
    TWILIGHT_LORD_KELRIS,
    AKU_MAI,
    // Gnomeregan
    LEPER_GNOME,
    IRRADIATED_PILLAGER,
    CAVERNDEEP_BURROWER,
    IRRADIATED_SLIME,
    DARK_IRON_AGENT,
    MECHANO_TANK,
    ARCANE_NULLIFIER,
    WALKING_BOMB,
    GRUBBIS,
    VISCOUS_FALLOUT,
    ELECTROCUTIONER_6000,
    CROWD_PUMMELER,
    MEKGINEER_THERMAPLUGG,
    // Hillsbrad Foothills
    GRAY_BEAR,
    MOUNTAIN_LION,
    SYNDICATE_FOOTPAD,
    SYNDICATE_THIEF,
    SYNDICATE_SHADOW_MAGE,
    SYNDICATE_ENFORCER,
    GRAVIS_SLIPKNOT,
    CRUSHRIDGE_OGRE,
    CRUSHRIDGE_MAGE,
    CRUSHRIDGE_ENFORCER,
    FORSAKEN_THUG,
    FORSAKEN_HERBALIST,
    FORSAKEN_COURIER,
    MOUNTAIN_YETI,
    BLOODFANG,
    TORN_FIN_TIDEHUNTER,
    TORN_FIN_ORACLE,
    // Tirisfal Glades and the Graveyard
    SCARLET_CONVERT,
    SCARLET_SCOUT,
    SCARLET_TORTURER,
    HAUNTING_PHANTASM,
    UNFETTERED_SPIRIT,
    INTERROGATOR_VISHAS,
    AZSHIR_THE_SLEEPLESS,
    BLOODMAGE_THALNOS,
    IRONSPINE,
    // The Library
    SCARLET_GALLANT,
    SCARLET_ADEPT,
    SCARLET_MONK,
    SCARLET_BEASTMASTER,
    SCARLET_CHAPLAIN,
    SCARLET_DIVINER,
    SCARLET_TRACKING_HOUND,
    HOUNDMASTER_LOKSEY,
    ARCANIST_DOAN,
    // Stranglethorn Vale
    STRANGLETHORN_TIGER,
    SHADOWMAW_PANTHER,
    KING_BANGALASH,
    STRANGLETHORN_RAPTOR,
    LASHTAIL_RAPTOR,
    MISTVALE_GORILLA,
    ELDER_MISTVALE_GORILLA,
    BLOODSCALP_WARRIOR,
    BLOODSCALP_SHAMAN,
    BLOODSCALP_HEADHUNTER,
    MOGH_THE_UNDYING,
    BLOODSAIL_SWASHBUCKLER,
    BLOODSAIL_MAGE,
    BLOODSAIL_SEA_DOG,
    FLEET_MASTER_FIRALLON,
    // The Armory
    SCARLET_SOLDIER,
    SCARLET_MYRMIDON,
    SCARLET_DEFENDER,
    SCARLET_TRAINEE,
    HEROD,
    // The Cathedral
    SCARLET_CHAMPION,
    SCARLET_ABBOT,
    SCARLET_WIZARD,
    SCARLET_CENTURION,
    HIGH_INQUISITOR_FAIRBANKS,
    SCARLET_COMMANDER_MOGRAINE,
    HIGH_INQUISITOR_WHITEMANE,
    // Tanaris
    WASTEWANDER_BANDIT,
    WASTEWANDER_THIEF,
    WASTEWANDER_SHADOW_MAGE,
    CALIPH_SCORPIDSTING,
    BLISTERPAW_HYENA,
    SCORPID_HUNTER,
    SCORPID_REAVER,
    DUNEMAUL_BRUTE,
    DUNEMAUL_OGRE_MAGE,
    OMGORN_THE_LOST,
    SOUTHSEA_PIRATE,
    SOUTHSEA_CANNONEER,
    ANDRE_FIREBEARD,
    SANDFURY_HIDESKINNER,
    SANDFURY_AXE_THROWER,
    // Thousand Needles
    GALAK_SCOUT,
    GALAK_WINDCHASER,
    SALTSTONE_BASILISK,
    // Razorfen Kraul
    RAZORFEN_QUILGUARD,
    RAZORFEN_GEOMANCER,
    RAZORFEN_TOTEMIC,
    RAGING_AGAMAR,
    AGGEM_THORNCURSE,
    DEATH_SPEAKER_JARGBA,
    OVERLORD_RAMTUSK,
    AGATHELOS_THE_RAGING,
    CHARLGA_RAZORFLANK,
    // Razorfen Downs
    DEATHS_HEAD_ACOLYTE,
    WITHERED_QUILGUARD,
    SKELETAL_FROSTWEAVER,
    SPLINTERBONE_WARRIOR,
    TOMB_FIEND,
    TUTEN_KASH,
    MORDRESH_FIRE_EYE,
    GLUTTON,
    FROZEN_SPECTRE,
    AMNENNAR_THE_COLDBRINGER,
    // Zul'Farrak
    SANDFURY_SHADOWCASTER,
    SANDFURY_BLOOD_DRINKER,
    ZULFARRAK_ZOMBIE,
    SCARAB,
    SULLITHUZ_BROODLING,
    ANTU_SUL,
    THEKA_THE_MARTYR,
    WITCH_DOCTOR_ZUM_RAH,
    GAHZ_RILLA,
    NEKRUM_GUTCHEWER,
    SHADOWPRIEST_SEZZ_ZIZ,
    RUUZLU,
    CHIEF_UKORZ_SANDSCALP,
    SANDFURY_SLAVE,
    SANDFURY_DRUDGE,
    COUNT
};

}

#endif
