// Generated by tools/gen_effects.py. Do not edit by hand.
#ifndef GW_ICONS_H
#define GW_ICONS_H

#include "bn_color.h"
#include "bn_sprite_palette_item.h"

namespace gw
{

// Frames of bn::sprite_items::fx_icons.
enum class icon_id : uint8_t
{
    HEROIC_STRIKE,
    BATTLE_SHOUT,
    CHARGE,
    REND,
    THUNDER_CLAP,
    HAMSTRING,
    EXECUTE,
    MORTAL_STRIKE,
    BLOODTHIRST,
    SHIELD_BLOCK,
    FIREBALL,
    FROST_ARMOR,
    FROSTBOLT,
    FIRE_BLAST,
    ARCANE_MISSILES,
    FROST_NOVA,
    ARCANE_EXPLOSION,
    PYROBLAST,
    ICE_BARRIER,
    ARCANE_INTELLECT,
    RAPTOR_STRIKE,
    SERPENT_STING,
    ARCANE_SHOT,
    HUNTERS_MARK,
    CONCUSSIVE_SHOT,
    ASPECT_HAWK,
    MULTI_SHOT,
    AIMED_SHOT,
    AUTO_SHOT,
    ATTACK,
    POTION,
    FOOD,
    DRINK,
    COUNT
};

namespace palettes
{
    // fx_icons with every color grayed out, for abilities that can't be used yet.
    constexpr bn::color icons_gray_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 3), bn::color(18, 18, 18), bn::color(14, 14, 14), bn::color(8, 8, 8), bn::color(6, 6, 6), bn::color(9, 9, 9), bn::color(13, 13, 13), bn::color(16, 16, 16), bn::color(6, 6, 6), bn::color(13, 13, 13), bn::color(6, 6, 6), bn::color(13, 13, 13), bn::color(7, 7, 7), bn::color(13, 13, 13), bn::color(9, 9, 9) };
    constexpr bn::sprite_palette_item icons_gray(icons_gray_colors, bn::bpp_mode::BPP_4);
}

}

#endif
