// Generated by tools/gen_characters.py. Do not edit by hand.
// Include only from gw_looks.cpp: it pulls in every character sheet.
#ifndef GW_LOOKS_DATA_H
#define GW_LOOKS_DATA_H

#include "bn_sprite_items_char_boar.h"
#include "bn_sprite_items_char_dwarf_bow.h"
#include "bn_sprite_items_char_dwarf_sword.h"
#include "bn_sprite_items_char_elf_bow.h"
#include "bn_sprite_items_char_elf_sword.h"
#include "bn_sprite_items_char_fem_robe.h"
#include "bn_sprite_items_char_fem_sword.h"
#include "bn_sprite_items_char_gnoll.h"
#include "bn_sprite_items_char_goblin.h"
#include "bn_sprite_items_char_hum_plain.h"
#include "bn_sprite_items_char_hum_robe.h"
#include "bn_sprite_items_char_hum_staff.h"
#include "bn_sprite_items_char_hum_sword.h"
#include "bn_sprite_items_char_kobold.h"
#include "bn_sprite_items_char_kobold_candle.h"
#include "bn_sprite_items_char_murloc.h"
#include "bn_sprite_items_char_spider.h"
#include "bn_sprite_items_char_watcher.h"
#include "bn_sprite_items_char_water_elemental.h"
#include "bn_sprite_items_char_wolf.h"

#include "gw_looks.h"
#include "gw_palettes.h"

namespace gw
{

constexpr look_def look_table[] = {
    { bn::sprite_items::char_hum_sword, palettes::human_warrior, false },
    { bn::sprite_items::char_hum_staff, palettes::human_mage, false },
    { bn::sprite_items::char_dwarf_sword, palettes::dwarf_warrior, false },
    { bn::sprite_items::char_dwarf_bow, palettes::dwarf_hunter, false },
    { bn::sprite_items::char_elf_sword, palettes::elf_warrior, false },
    { bn::sprite_items::char_elf_bow, palettes::elf_hunter, false },
    { bn::sprite_items::char_hum_sword, palettes::guard, false },
    { bn::sprite_items::char_hum_sword, palettes::marshal, false },
    { bn::sprite_items::char_hum_sword, palettes::trainer_warrior, false },
    { bn::sprite_items::char_fem_sword, palettes::trainer_warrior_f, false },
    { bn::sprite_items::char_hum_robe, palettes::priest, false },
    { bn::sprite_items::char_hum_staff, palettes::mage_trainer, false },
    { bn::sprite_items::char_dwarf_bow, palettes::hunter_trainer, false },
    { bn::sprite_items::char_hum_robe, palettes::innkeeper, false },
    { bn::sprite_items::char_hum_robe, palettes::merchant, false },
    { bn::sprite_items::char_fem_robe, palettes::smith, false },
    { bn::sprite_items::char_fem_robe, palettes::farmer_f, false },
    { bn::sprite_items::char_fem_robe, palettes::farmer_f2, false },
    { bn::sprite_items::char_hum_sword, palettes::militia, false },
    { bn::sprite_items::char_hum_plain, palettes::peasant, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_thug, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_trapper, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_smuggler, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_miner, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_pirate, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_blackguard, false },
    { bn::sprite_items::char_hum_sword, palettes::vancleef, false },
    { bn::sprite_items::char_hum_sword, palettes::stormwind_guard, false },
    { bn::sprite_items::char_hum_sword, palettes::bolvar, false },
    { bn::sprite_items::char_hum_robe, palettes::archbishop, false },
    { bn::sprite_items::char_dwarf_bow, palettes::explorer, false },
    { bn::sprite_items::char_fem_robe, palettes::innkeeper_f, false },
    { bn::sprite_items::char_hum_sword, palettes::warden, false },
    { bn::sprite_items::char_hum_plain, palettes::defias_prisoner, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_convict, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_insurgent, false },
    { bn::sprite_items::char_hum_sword, palettes::targorr, false },
    { bn::sprite_items::char_dwarf_sword, palettes::kam_deepfury, false },
    { bn::sprite_items::char_hum_sword, palettes::bazil_thredd, false },
    { bn::sprite_items::char_dwarf_sword, palettes::gryphon_master, false },
    { bn::sprite_items::char_hum_plain, palettes::riding_trainer, false },
    { bn::sprite_items::char_dwarf_sword, palettes::tram_conductor, false },
    { bn::sprite_items::char_wolf, palettes::young_wolf, true },
    { bn::sprite_items::char_wolf, palettes::timber_wolf, true },
    { bn::sprite_items::char_boar, palettes::boar, true },
    { bn::sprite_items::char_boar, palettes::princess, true },
    { bn::sprite_items::char_spider, palettes::forest_spider, true },
    { bn::sprite_items::char_kobold, palettes::kobold_vermin, true },
    { bn::sprite_items::char_kobold_candle, palettes::kobold_tunneler, true },
    { bn::sprite_items::char_murloc, palettes::murloc, true },
    { bn::sprite_items::char_gnoll, palettes::riverpaw_gnoll, true },
    { bn::sprite_items::char_gnoll, palettes::hogger, true },
    { bn::sprite_items::char_gnoll, palettes::gnoll_brute, true },
    { bn::sprite_items::char_watcher, palettes::harvest_watcher, true },
    { bn::sprite_items::char_goblin, palettes::goblin_engineer, true },
    { bn::sprite_items::char_goblin, palettes::sneed, true },
    { bn::sprite_items::char_water_elemental, palettes::water_elemental, true },
};

static_assert(sizeof(look_table) / sizeof(look_table[0]) == int(look_id::COUNT));

}

#endif
