// Generated by tools/gen_characters.py. Do not edit by hand.
// Include only from gw_looks.cpp: it pulls in every character sheet.
#ifndef GW_LOOKS_DATA_H
#define GW_LOOKS_DATA_H

#include "bn_sprite_items_char_abomination.h"
#include "bn_sprite_items_char_bear.h"
#include "bn_sprite_items_char_boar.h"
#include "bn_sprite_items_char_bomb.h"
#include "bn_sprite_items_char_cat.h"
#include "bn_sprite_items_char_crocolisk.h"
#include "bn_sprite_items_char_dwarf_bow.h"
#include "bn_sprite_items_char_dwarf_plain.h"
#include "bn_sprite_items_char_dwarf_sword.h"
#include "bn_sprite_items_char_elf_bow.h"
#include "bn_sprite_items_char_elf_sword.h"
#include "bn_sprite_items_char_fem_bow.h"
#include "bn_sprite_items_char_fem_robe.h"
#include "bn_sprite_items_char_fem_sword.h"
#include "bn_sprite_items_char_ghoul.h"
#include "bn_sprite_items_char_gnoll.h"
#include "bn_sprite_items_char_gnome_plain.h"
#include "bn_sprite_items_char_gnome_sword.h"
#include "bn_sprite_items_char_goblin.h"
#include "bn_sprite_items_char_hum_plain.h"
#include "bn_sprite_items_char_hum_robe.h"
#include "bn_sprite_items_char_hum_staff.h"
#include "bn_sprite_items_char_hum_sword.h"
#include "bn_sprite_items_char_hydra.h"
#include "bn_sprite_items_char_kobold.h"
#include "bn_sprite_items_char_kobold_candle.h"
#include "bn_sprite_items_char_murloc.h"
#include "bn_sprite_items_char_naga.h"
#include "bn_sprite_items_char_naga_caster.h"
#include "bn_sprite_items_char_ogre.h"
#include "bn_sprite_items_char_ooze.h"
#include "bn_sprite_items_char_orc_staff.h"
#include "bn_sprite_items_char_orc_sword.h"
#include "bn_sprite_items_char_raptor.h"
#include "bn_sprite_items_char_robot.h"
#include "bn_sprite_items_char_skeleton.h"
#include "bn_sprite_items_char_skeleton_mage.h"
#include "bn_sprite_items_char_spider.h"
#include "bn_sprite_items_char_spirit.h"
#include "bn_sprite_items_char_trogg.h"
#include "bn_sprite_items_char_turtle.h"
#include "bn_sprite_items_char_watcher.h"
#include "bn_sprite_items_char_water_elemental.h"
#include "bn_sprite_items_char_wolf.h"
#include "bn_sprite_items_char_worgen.h"
#include "bn_sprite_items_char_worgen_caster.h"
#include "bn_sprite_items_char_yeti.h"

#include "gw_looks.h"
#include "gw_palettes.h"

namespace gw
{

constexpr look_def look_table[] = {
    { bn::sprite_items::char_hum_sword, palettes::human_warrior, false },
    { bn::sprite_items::char_hum_staff, palettes::human_mage, false },
    { bn::sprite_items::char_dwarf_sword, palettes::dwarf_warrior, false },
    { bn::sprite_items::char_dwarf_bow, palettes::dwarf_hunter, false },
    { bn::sprite_items::char_elf_sword, palettes::elf_warrior, false },
    { bn::sprite_items::char_elf_bow, palettes::elf_hunter, false },
    { bn::sprite_items::char_hum_sword, palettes::guard, false },
    { bn::sprite_items::char_hum_sword, palettes::marshal, false },
    { bn::sprite_items::char_hum_sword, palettes::trainer_warrior, false },
    { bn::sprite_items::char_fem_sword, palettes::trainer_warrior_f, false },
    { bn::sprite_items::char_hum_robe, palettes::priest, false },
    { bn::sprite_items::char_hum_staff, palettes::mage_trainer, false },
    { bn::sprite_items::char_dwarf_bow, palettes::hunter_trainer, false },
    { bn::sprite_items::char_hum_robe, palettes::innkeeper, false },
    { bn::sprite_items::char_hum_robe, palettes::merchant, false },
    { bn::sprite_items::char_fem_robe, palettes::smith, false },
    { bn::sprite_items::char_fem_robe, palettes::farmer_f, false },
    { bn::sprite_items::char_fem_robe, palettes::farmer_f2, false },
    { bn::sprite_items::char_hum_sword, palettes::militia, false },
    { bn::sprite_items::char_hum_plain, palettes::peasant, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_thug, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_trapper, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_smuggler, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_miner, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_pirate, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_blackguard, false },
    { bn::sprite_items::char_hum_sword, palettes::vancleef, false },
    { bn::sprite_items::char_hum_sword, palettes::stormwind_guard, false },
    { bn::sprite_items::char_hum_sword, palettes::bolvar, false },
    { bn::sprite_items::char_hum_robe, palettes::archbishop, false },
    { bn::sprite_items::char_dwarf_bow, palettes::explorer, false },
    { bn::sprite_items::char_fem_robe, palettes::innkeeper_f, false },
    { bn::sprite_items::char_hum_sword, palettes::warden, false },
    { bn::sprite_items::char_hum_plain, palettes::defias_prisoner, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_convict, false },
    { bn::sprite_items::char_hum_sword, palettes::defias_insurgent, false },
    { bn::sprite_items::char_hum_sword, palettes::targorr, false },
    { bn::sprite_items::char_dwarf_sword, palettes::kam_deepfury, false },
    { bn::sprite_items::char_hum_sword, palettes::bazil_thredd, false },
    { bn::sprite_items::char_dwarf_sword, palettes::gryphon_master, false },
    { bn::sprite_items::char_hum_plain, palettes::riding_trainer, false },
    { bn::sprite_items::char_dwarf_sword, palettes::tram_conductor, false },
    { bn::sprite_items::char_hum_robe, palettes::magistrate, false },
    { bn::sprite_items::char_hum_plain, palettes::foreman, false },
    { bn::sprite_items::char_hum_plain, palettes::dockmaster, false },
    { bn::sprite_items::char_fem_robe, palettes::chef_f, false },
    { bn::sprite_items::char_hum_plain, palettes::fisherman, false },
    { bn::sprite_items::char_fem_robe, palettes::gryphon_master_f, false },
    { bn::sprite_items::char_orc_sword, palettes::blackrock_outrunner, false },
    { bn::sprite_items::char_orc_sword, palettes::blackrock_grunt, false },
    { bn::sprite_items::char_orc_staff, palettes::blackrock_shadowcaster, false },
    { bn::sprite_items::char_orc_sword, palettes::blackrock_renegade, false },
    { bn::sprite_items::char_orc_staff, palettes::blackrock_summoner, false },
    { bn::sprite_items::char_orc_sword, palettes::gath_ilzogg, false },
    { bn::sprite_items::char_hum_sword, palettes::ello_ebonlocke, false },
    { bn::sprite_items::char_fem_sword, palettes::althea_ebonlocke, false },
    { bn::sprite_items::char_hum_sword, palettes::night_watch, false },
    { bn::sprite_items::char_fem_robe, palettes::madame_eva, false },
    { bn::sprite_items::char_fem_robe, palettes::sirra_von_indi, false },
    { bn::sprite_items::char_hum_plain, palettes::sven_yorgen, false },
    { bn::sprite_items::char_hum_plain, palettes::calor, false },
    { bn::sprite_items::char_hum_robe, palettes::abercrombie, false },
    { bn::sprite_items::char_hum_robe, palettes::trelayne, false },
    { bn::sprite_items::char_fem_robe, palettes::felicia_maline, false },
    { bn::sprite_items::char_elf_bow, palettes::ranger_valdan, false },
    { bn::sprite_items::char_hum_robe, palettes::stalvan_mistmantle, false },
    { bn::sprite_items::char_hum_robe, palettes::morbent_fel, false },
    { bn::sprite_items::char_hum_plain, palettes::haunted_servitor, false },
    { bn::sprite_items::char_hum_sword, palettes::wailing_guardsman, false },
    { bn::sprite_items::char_hum_sword, palettes::razorclaw_the_butcher, false },
    { bn::sprite_items::char_hum_sword, palettes::baron_silverlaine, false },
    { bn::sprite_items::char_hum_sword, palettes::commander_springvale, false },
    { bn::sprite_items::char_hum_staff, palettes::archmage_arugal, false },
    { bn::sprite_items::char_dwarf_sword, palettes::magni_bronzebeard, false },
    { bn::sprite_items::char_dwarf_sword, palettes::ironforge_guard, false },
    { bn::sprite_items::char_dwarf_plain, palettes::dwarf_innkeeper, false },
    { bn::sprite_items::char_dwarf_plain, palettes::dwarf_merchant, false },
    { bn::sprite_items::char_dwarf_plain, palettes::dwarf_smith, false },
    { bn::sprite_items::char_dwarf_sword, palettes::captain_stoutfist, false },
    { bn::sprite_items::char_dwarf_bow, palettes::ormer_ironbraid, false },
    { bn::sprite_items::char_dwarf_plain, palettes::prospector_whelgar, false },
    { bn::sprite_items::char_dwarf_sword, palettes::dark_iron_dwarf, false },
    { bn::sprite_items::char_dwarf_plain, palettes::dark_iron_saboteur, false },
    { bn::sprite_items::char_dwarf_sword, palettes::balgaras_the_foul, false },
    { bn::sprite_items::char_dwarf_sword, palettes::dark_iron_agent, false },
    { bn::sprite_items::char_orc_sword, palettes::dragonmaw_grunt, false },
    { bn::sprite_items::char_orc_staff, palettes::dragonmaw_shadowwarder, false },
    { bn::sprite_items::char_orc_sword, palettes::nek_rosh, false },
    { bn::sprite_items::char_hum_robe, palettes::twilight_acolyte, false },
    { bn::sprite_items::char_hum_sword, palettes::twilight_reaver, false },
    { bn::sprite_items::char_hum_staff, palettes::twilight_lord_kelris, false },
    { bn::sprite_items::char_hum_sword, palettes::menethil_guard, false },
    { bn::sprite_items::char_hum_plain, palettes::james_halloran, false },
    { bn::sprite_items::char_fem_bow, palettes::sentinel, false },
    { bn::sprite_items::char_fem_robe, palettes::dawnwatcher_shaedlass, false },
    { bn::sprite_items::char_elf_sword, palettes::argent_guard_thaelrid, false },
    { bn::sprite_items::char_fem_robe, palettes::hippogryph_master, false },
    { bn::sprite_items::char_fem_robe, palettes::night_elf_innkeeper, false },
    { bn::sprite_items::char_gnome_plain, palettes::mekkatorque, false },
    { bn::sprite_items::char_gnome_plain, palettes::tinker_gnome, false },
    { bn::sprite_items::char_gnome_plain, palettes::ozzie_togglevolt, false },
    { bn::sprite_items::char_gnome_sword, palettes::leper_gnome, false },
    { bn::sprite_items::char_gnome_sword, palettes::mekgineer_thermaplugg, false },
    { bn::sprite_items::char_hum_plain, palettes::magistrate_maleb, false },
    { bn::sprite_items::char_hum_sword, palettes::raleigh_the_devout, false },
    { bn::sprite_items::char_hum_robe, palettes::loremaster_dibbs, false },
    { bn::sprite_items::char_hum_sword, palettes::darren_malvew, false },
    { bn::sprite_items::char_hum_sword, palettes::syndicate_footpad, false },
    { bn::sprite_items::char_hum_plain, palettes::syndicate_thief, false },
    { bn::sprite_items::char_hum_robe, palettes::syndicate_shadow_mage, false },
    { bn::sprite_items::char_hum_sword, palettes::syndicate_enforcer, false },
    { bn::sprite_items::char_hum_sword, palettes::gravis_slipknot, false },
    { bn::sprite_items::char_hum_sword, palettes::forsaken_thug, false },
    { bn::sprite_items::char_hum_robe, palettes::forsaken_herbalist, false },
    { bn::sprite_items::char_hum_plain, palettes::forsaken_courier, false },
    { bn::sprite_items::char_hum_plain, palettes::scarlet_convert, false },
    { bn::sprite_items::char_fem_bow, palettes::scarlet_scout, false },
    { bn::sprite_items::char_hum_sword, palettes::scarlet_torturer, false },
    { bn::sprite_items::char_hum_plain, palettes::interrogator_vishas, false },
    { bn::sprite_items::char_hum_robe, palettes::bloodmage_thalnos, false },
    { bn::sprite_items::char_hum_sword, palettes::scarlet_gallant, false },
    { bn::sprite_items::char_hum_robe, palettes::scarlet_adept, false },
    { bn::sprite_items::char_hum_plain, palettes::scarlet_monk, false },
    { bn::sprite_items::char_fem_bow, palettes::scarlet_beastmaster, false },
    { bn::sprite_items::char_fem_robe, palettes::scarlet_chaplain, false },
    { bn::sprite_items::char_hum_staff, palettes::scarlet_diviner, false },
    { bn::sprite_items::char_hum_sword, palettes::houndmaster_loksey, false },
    { bn::sprite_items::char_hum_staff, palettes::arcanist_doan, false },
    { bn::sprite_items::char_hum_robe, palettes::southshore_innkeeper, false },
    { bn::sprite_items::char_elf_bow, palettes::argent_scout, false },
    { bn::sprite_items::char_wolf, palettes::young_wolf, true },
    { bn::sprite_items::char_wolf, palettes::timber_wolf, true },
    { bn::sprite_items::char_boar, palettes::boar, true },
    { bn::sprite_items::char_boar, palettes::princess, true },
    { bn::sprite_items::char_spider, palettes::forest_spider, true },
    { bn::sprite_items::char_kobold, palettes::kobold_vermin, true },
    { bn::sprite_items::char_kobold_candle, palettes::kobold_tunneler, true },
    { bn::sprite_items::char_murloc, palettes::murloc, true },
    { bn::sprite_items::char_gnoll, palettes::riverpaw_gnoll, true },
    { bn::sprite_items::char_gnoll, palettes::hogger, true },
    { bn::sprite_items::char_gnoll, palettes::gnoll_brute, true },
    { bn::sprite_items::char_watcher, palettes::harvest_watcher, true },
    { bn::sprite_items::char_goblin, palettes::goblin_engineer, true },
    { bn::sprite_items::char_goblin, palettes::sneed, true },
    { bn::sprite_items::char_water_elemental, palettes::water_elemental, true },
    { bn::sprite_items::char_gnoll, palettes::redridge_mongrel, true },
    { bn::sprite_items::char_gnoll, palettes::shadowhide_gnoll, true },
    { bn::sprite_items::char_gnoll, palettes::shadowhide_mystic, true },
    { bn::sprite_items::char_gnoll, palettes::ribchaser, true },
    { bn::sprite_items::char_murloc, palettes::murloc_flesheater, true },
    { bn::sprite_items::char_boar, palettes::great_goretusk, true },
    { bn::sprite_items::char_boar, palettes::bellygrub, true },
    { bn::sprite_items::char_spider, palettes::tarantula, true },
    { bn::sprite_items::char_wolf, palettes::dire_wolf, true },
    { bn::sprite_items::char_wolf, palettes::rabid_dire_wolf, true },
    { bn::sprite_items::char_spider, palettes::venom_web_spider, true },
    { bn::sprite_items::char_wolf, palettes::bleak_worg, true },
    { bn::sprite_items::char_worgen, palettes::nightbane_dark_runner, true },
    { bn::sprite_items::char_worgen_caster, palettes::nightbane_shadow_weaver, true },
    { bn::sprite_items::char_worgen, palettes::nightbane_tainted_one, true },
    { bn::sprite_items::char_worgen, palettes::shadowfang_moonwalker, true },
    { bn::sprite_items::char_worgen_caster, palettes::shadowfang_darkcaster, true },
    { bn::sprite_items::char_worgen, palettes::shadowfang_wolfguard, true },
    { bn::sprite_items::char_worgen, palettes::rethilgore, true },
    { bn::sprite_items::char_worgen, palettes::odo_the_blindwatcher, true },
    { bn::sprite_items::char_skeleton, palettes::skeletal_warrior, true },
    { bn::sprite_items::char_skeleton_mage, palettes::skeletal_mage, true },
    { bn::sprite_items::char_skeleton, palettes::skeletal_servant, true },
    { bn::sprite_items::char_skeleton, palettes::mor_ladim, true },
    { bn::sprite_items::char_ghoul, palettes::rotting_ghoul, true },
    { bn::sprite_items::char_ghoul, palettes::plague_spreader, true },
    { bn::sprite_items::char_ogre, palettes::splinter_fist_ogre, true },
    { bn::sprite_items::char_ogre, palettes::splinter_fist_taskmaster, true },
    { bn::sprite_items::char_abomination, palettes::stitches, true },
    { bn::sprite_items::char_crocolisk, palettes::young_crocolisk, true },
    { bn::sprite_items::char_crocolisk, palettes::giant_crocolisk, true },
    { bn::sprite_items::char_raptor, palettes::mottled_raptor, true },
    { bn::sprite_items::char_raptor, palettes::mottled_screecher, true },
    { bn::sprite_items::char_raptor, palettes::sarltooth, true },
    { bn::sprite_items::char_gnoll, palettes::mosshide_gnoll, true },
    { bn::sprite_items::char_gnoll, palettes::mosshide_mystic, true },
    { bn::sprite_items::char_murloc, palettes::bluegill_murloc, true },
    { bn::sprite_items::char_murloc, palettes::gelihast, true },
    { bn::sprite_items::char_murloc, palettes::blindlight_murloc, true },
    { bn::sprite_items::char_naga, palettes::blackfathom_myrmidon, true },
    { bn::sprite_items::char_naga_caster, palettes::blackfathom_tide_priestess, true },
    { bn::sprite_items::char_naga_caster, palettes::lady_sarevess, true },
    { bn::sprite_items::char_turtle, palettes::aku_mai_snapjaw, true },
    { bn::sprite_items::char_turtle, palettes::ghamoo_ra, true },
    { bn::sprite_items::char_hydra, palettes::aku_mai_servant, true },
    { bn::sprite_items::char_hydra, palettes::aku_mai, true },
    { bn::sprite_items::char_trogg, palettes::irradiated_pillager, true },
    { bn::sprite_items::char_trogg, palettes::caverndeep_burrower, true },
    { bn::sprite_items::char_trogg, palettes::grubbis, true },
    { bn::sprite_items::char_ooze, palettes::irradiated_slime, true },
    { bn::sprite_items::char_ooze, palettes::viscous_fallout, true },
    { bn::sprite_items::char_robot, palettes::mechano_tank, true },
    { bn::sprite_items::char_robot, palettes::arcane_nullifier, true },
    { bn::sprite_items::char_robot, palettes::electrocutioner_6000, true },
    { bn::sprite_items::char_robot, palettes::crowd_pummeler, true },
    { bn::sprite_items::char_bomb, palettes::walking_bomb, true },
    { bn::sprite_items::char_bear, palettes::gray_bear, true },
    { bn::sprite_items::char_cat, palettes::mountain_lion, true },
    { bn::sprite_items::char_yeti, palettes::mountain_yeti, true },
    { bn::sprite_items::char_yeti, palettes::bloodfang, true },
    { bn::sprite_items::char_ogre, palettes::crushridge_ogre, true },
    { bn::sprite_items::char_ogre, palettes::crushridge_mage, true },
    { bn::sprite_items::char_ogre, palettes::crushridge_enforcer, true },
    { bn::sprite_items::char_murloc, palettes::torn_fin_tidehunter, true },
    { bn::sprite_items::char_murloc, palettes::torn_fin_oracle, true },
    { bn::sprite_items::char_spirit, palettes::haunting_phantasm, true },
    { bn::sprite_items::char_spirit, palettes::unfettered_spirit, true },
    { bn::sprite_items::char_spirit, palettes::azshir_the_sleepless, true },
    { bn::sprite_items::char_skeleton, palettes::ironspine, true },
    { bn::sprite_items::char_wolf, palettes::scarlet_tracking_hound, true },
};

static_assert(sizeof(look_table) / sizeof(look_table[0]) == int(look_id::COUNT));

}

#endif
