// Generated by tools/gen_characters.py. Do not edit by hand.
#ifndef GW_LOOK_IDS_H
#define GW_LOOK_IDS_H

#include <cstdint>

namespace gw
{

enum class look_id : uint8_t
{
    HUMAN_WARRIOR,
    HUMAN_MAGE,
    DWARF_WARRIOR,
    DWARF_HUNTER,
    ELF_WARRIOR,
    ELF_HUNTER,
    GUARD,
    MARSHAL,
    TRAINER_WARRIOR,
    TRAINER_WARRIOR_F,
    PRIEST,
    MAGE_TRAINER,
    HUNTER_TRAINER,
    INNKEEPER,
    MERCHANT,
    SMITH,
    FARMER_F,
    FARMER_F2,
    MILITIA,
    PEASANT,
    DEFIAS_THUG,
    DEFIAS_TRAPPER,
    DEFIAS_SMUGGLER,
    DEFIAS_MINER,
    DEFIAS_PIRATE,
    DEFIAS_BLACKGUARD,
    VANCLEEF,
    YOUNG_WOLF,
    TIMBER_WOLF,
    BOAR,
    PRINCESS,
    FOREST_SPIDER,
    KOBOLD_VERMIN,
    KOBOLD_TUNNELER,
    MURLOC,
    RIVERPAW_GNOLL,
    HOGGER,
    GNOLL_BRUTE,
    HARVEST_WATCHER,
    GOBLIN_ENGINEER,
    SNEED,
    COUNT
};

}

#endif
