// Generated by tools/gen_world.py. Do not edit by hand.
// Include only from gw_menu_map.cpp: it pulls in every minimap picture.
#ifndef GW_MINIMAPS_H
#define GW_MINIMAPS_H

#include "bn_sprite_items_minimap_deadmines.h"
#include "bn_sprite_items_minimap_echo_ridge.h"
#include "bn_sprite_items_minimap_elwynn.h"
#include "bn_sprite_items_minimap_fargodeep.h"
#include "bn_sprite_items_minimap_stockade.h"
#include "bn_sprite_items_minimap_stormwind.h"
#include "bn_sprite_items_minimap_westfall.h"

#include "gw_ids.h"

namespace gw
{

// A 128x128 picture of a map in four 64x64 frames. A world pixel (x, y) is the picture pixel
// (left + x * minimap_content / size, top + y * minimap_content / size).
struct minimap_def
{
    map_id map;
    const bn::sprite_item& item;
    int left;
    int top;
    int size;
};

constexpr int minimap_picture = 128;
constexpr int minimap_content = 112;

constexpr minimap_def minimaps[] = {
    { map_id::ELWYNN, bn::sprite_items::minimap_elwynn, 8, 8, 2048 },
    { map_id::STORMWIND, bn::sprite_items::minimap_stormwind, 8, 8, 1024 },
    { map_id::WESTFALL, bn::sprite_items::minimap_westfall, 8, 8, 1024 },
    { map_id::ECHO_RIDGE, bn::sprite_items::minimap_echo_ridge, 8, 8, 512 },
    { map_id::FARGODEEP, bn::sprite_items::minimap_fargodeep, 8, 26, 768 },
    { map_id::DEADMINES, bn::sprite_items::minimap_deadmines, 8, 36, 1024 },
    { map_id::STOCKADE, bn::sprite_items::minimap_stockade, 8, 36, 1024 },
};

constexpr int minimap_count = sizeof(minimaps) / sizeof(minimaps[0]);

}

#endif
