// Generated by tools/gen_characters.py. Do not edit by hand.
#ifndef GW_PALETTES_H
#define GW_PALETTES_H

#include "bn_color.h"
#include "bn_sprite_palette_item.h"

namespace gw::palettes
{
    constexpr bn::color human_warrior_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(10, 6, 3), bn::color(18, 11, 5), bn::color(11, 11, 13), bn::color(18, 19, 21), bn::color(23, 25, 27), bn::color(4, 6, 13), bn::color(7, 11, 23), bn::color(29, 23, 8), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(20, 16, 5), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item human_warrior(human_warrior_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color human_mage_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(15, 12, 5), bn::color(25, 20, 9), bn::color(9, 4, 13), bn::color(15, 8, 21), bn::color(22, 15, 27), bn::color(6, 3, 10), bn::color(11, 5, 17), bn::color(29, 25, 12), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(20, 17, 8), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item human_mage(human_mage_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color dwarf_warrior_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 20, 16), bn::color(12, 5, 2), bn::color(21, 9, 4), bn::color(11, 11, 12), bn::color(19, 19, 20), bn::color(25, 25, 26), bn::color(12, 3, 3), bn::color(20, 6, 5), bn::color(29, 23, 8), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(20, 16, 5), bn::color(21, 9, 4) };
    constexpr bn::sprite_palette_item dwarf_warrior(dwarf_warrior_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color dwarf_hunter_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 20, 16), bn::color(7, 4, 2), bn::color(12, 7, 4), bn::color(10, 8, 4), bn::color(17, 13, 8), bn::color(23, 19, 13), bn::color(4, 8, 4), bn::color(8, 14, 7), bn::color(25, 21, 12), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(17, 14, 8), bn::color(12, 7, 4) };
    constexpr bn::sprite_palette_item dwarf_hunter(dwarf_hunter_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color elf_warrior_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(16, 14, 21), bn::color(22, 19, 28), bn::color(5, 12, 11), bn::color(9, 21, 19), bn::color(10, 11, 13), bn::color(17, 18, 22), bn::color(22, 23, 29), bn::color(6, 3, 10), bn::color(11, 6, 17), bn::color(26, 26, 29), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(18, 18, 20), bn::color(22, 19, 29) };
    constexpr bn::sprite_palette_item elf_warrior(elf_warrior_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color elf_hunter_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(16, 14, 21), bn::color(22, 19, 28), bn::color(16, 16, 18), bn::color(28, 28, 30), bn::color(6, 8, 4), bn::color(10, 14, 8), bn::color(16, 20, 12), bn::color(3, 6, 3), bn::color(6, 10, 6), bn::color(23, 20, 13), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(16, 14, 9), bn::color(22, 19, 29) };
    constexpr bn::sprite_palette_item elf_hunter(elf_hunter_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color guard_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(9, 10, 12), bn::color(14, 15, 17), bn::color(11, 11, 13), bn::color(18, 19, 21), bn::color(23, 25, 27), bn::color(3, 5, 12), bn::color(6, 9, 21), bn::color(29, 23, 8), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(20, 16, 5), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item guard(guard_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color marshal_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(16, 16, 16), bn::color(27, 27, 28), bn::color(13, 13, 14), bn::color(21, 21, 23), bn::color(27, 27, 30), bn::color(3, 4, 11), bn::color(5, 8, 19), bn::color(31, 26, 9), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(21, 18, 6), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item marshal(marshal_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color trainer_warrior_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(4, 3, 1), bn::color(8, 5, 3), bn::color(11, 11, 13), bn::color(19, 19, 21), bn::color(25, 25, 27), bn::color(12, 3, 3), bn::color(21, 5, 5), bn::color(29, 23, 8), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(20, 16, 5), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item trainer_warrior(trainer_warrior_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color trainer_warrior_f_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(17, 15, 7), bn::color(29, 25, 13), bn::color(13, 13, 14), bn::color(21, 21, 23), bn::color(27, 27, 30), bn::color(12, 3, 3), bn::color(21, 5, 5), bn::color(29, 23, 8), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(20, 16, 5), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item trainer_warrior_f(trainer_warrior_f_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color priest_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(13, 13, 13), bn::color(22, 22, 22), bn::color(17, 17, 16), bn::color(28, 28, 27), bn::color(31, 31, 30), bn::color(15, 15, 14), bn::color(25, 25, 24), bn::color(29, 24, 9), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(20, 16, 6), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item priest(priest_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color mage_trainer_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(16, 16, 17), bn::color(28, 28, 29), bn::color(4, 5, 12), bn::color(8, 9, 20), bn::color(14, 15, 26), bn::color(3, 3, 9), bn::color(5, 6, 15), bn::color(25, 22, 31), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(17, 15, 21), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item mage_trainer(mage_trainer_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color hunter_trainer_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 20, 16), bn::color(16, 16, 16), bn::color(27, 27, 27), bn::color(9, 7, 4), bn::color(16, 12, 7), bn::color(21, 15, 9), bn::color(7, 5, 3), bn::color(12, 9, 5), bn::color(29, 23, 8), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(20, 16, 5), bn::color(27, 27, 27) };
    constexpr bn::sprite_palette_item hunter_trainer(hunter_trainer_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color innkeeper_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(7, 4, 1), bn::color(12, 7, 3), bn::color(13, 8, 4), bn::color(22, 14, 8), bn::color(26, 19, 13), bn::color(17, 16, 15), bn::color(29, 28, 25), bn::color(15, 10, 6), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(10, 7, 4), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item innkeeper(innkeeper_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color merchant_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(3, 2, 1), bn::color(6, 4, 3), bn::color(4, 9, 5), bn::color(7, 16, 9), bn::color(9, 21, 11), bn::color(3, 7, 4), bn::color(5, 12, 7), bn::color(29, 23, 8), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(20, 16, 5), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item merchant(merchant_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color smith_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(11, 4, 2), bn::color(19, 7, 4), bn::color(9, 6, 3), bn::color(15, 10, 6), bn::color(19, 13, 7), bn::color(7, 4, 3), bn::color(12, 8, 5), bn::color(20, 20, 21), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(14, 14, 14), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item smith(smith_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color farmer_f_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(10, 9, 9), bn::color(17, 16, 15), bn::color(13, 7, 5), bn::color(21, 12, 9), bn::color(27, 15, 11), bn::color(15, 12, 9), bn::color(25, 21, 15), bn::color(15, 10, 6), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(10, 7, 4), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item farmer_f(farmer_f_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color farmer_f2_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(13, 9, 3), bn::color(23, 15, 6), bn::color(7, 9, 12), bn::color(12, 15, 20), bn::color(15, 19, 26), bn::color(16, 15, 12), bn::color(27, 25, 20), bn::color(15, 10, 6), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(10, 7, 4), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item farmer_f2(farmer_f2_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color militia_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(12, 9, 3), bn::color(21, 15, 6), bn::color(11, 8, 4), bn::color(18, 13, 8), bn::color(24, 19, 13), bn::color(13, 11, 5), bn::color(22, 19, 9), bn::color(15, 10, 6), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(10, 7, 4), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item militia(militia_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color peasant_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(9, 5, 2), bn::color(15, 9, 4), bn::color(11, 8, 5), bn::color(19, 14, 9), bn::color(25, 18, 11), bn::color(14, 13, 9), bn::color(24, 22, 16), bn::color(15, 10, 6), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(10, 7, 4), bn::color(29, 21, 17) };
    constexpr bn::sprite_palette_item peasant(peasant_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color defias_thug_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(12, 3, 3), bn::color(21, 5, 5), bn::color(8, 6, 4), bn::color(13, 10, 8), bn::color(17, 13, 10), bn::color(6, 4, 3), bn::color(11, 8, 6), bn::color(21, 5, 5), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(14, 3, 3), bn::color(21, 5, 5) };
    constexpr bn::sprite_palette_item defias_thug(defias_thug_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color defias_trapper_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(11, 3, 3), bn::color(19, 5, 5), bn::color(6, 8, 4), bn::color(11, 13, 8), bn::color(14, 17, 10), bn::color(5, 6, 3), bn::color(9, 10, 6), bn::color(19, 5, 5), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(13, 3, 3), bn::color(19, 5, 5) };
    constexpr bn::sprite_palette_item defias_trapper(defias_trapper_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color defias_smuggler_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(19, 12, 9), bn::color(25, 17, 12), bn::color(13, 3, 3), bn::color(22, 6, 5), bn::color(6, 5, 7), bn::color(10, 9, 12), bn::color(13, 11, 15), bn::color(4, 4, 6), bn::color(8, 7, 10), bn::color(22, 6, 5), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(15, 4, 3), bn::color(22, 6, 5) };
    constexpr bn::sprite_palette_item defias_smuggler(defias_smuggler_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color defias_miner_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(19, 15, 5), bn::color(27, 23, 8), bn::color(8, 7, 6), bn::color(14, 12, 10), bn::color(18, 15, 13), bn::color(7, 6, 4), bn::color(12, 10, 8), bn::color(21, 5, 5), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(14, 3, 3), bn::color(21, 5, 5) };
    constexpr bn::sprite_palette_item defias_miner(defias_miner_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color defias_pirate_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(19, 12, 9), bn::color(25, 17, 12), bn::color(3, 3, 3), bn::color(5, 5, 6), bn::color(15, 15, 14), bn::color(25, 25, 24), bn::color(31, 31, 31), bn::color(3, 4, 9), bn::color(6, 8, 16), bn::color(21, 5, 5), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(14, 3, 3), bn::color(21, 5, 5) };
    constexpr bn::sprite_palette_item defias_pirate(defias_pirate_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color defias_blackguard_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(3, 2, 3), bn::color(5, 4, 5), bn::color(5, 4, 6), bn::color(9, 8, 10), bn::color(11, 10, 13), bn::color(3, 3, 4), bn::color(6, 5, 7), bn::color(19, 4, 5), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(13, 2, 3), bn::color(5, 4, 5) };
    constexpr bn::sprite_palette_item defias_blackguard(defias_blackguard_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color vancleef_colors[] = { bn::color(31, 0, 31), bn::color(3, 3, 4), bn::color(22, 15, 12), bn::color(29, 21, 16), bn::color(3, 2, 3), bn::color(6, 4, 5), bn::color(7, 2, 3), bn::color(12, 4, 5), bn::color(19, 7, 8), bn::color(3, 2, 3), bn::color(5, 4, 5), bn::color(29, 23, 8), bn::color(8, 5, 3), bn::color(15, 10, 6), bn::color(20, 16, 5), bn::color(22, 4, 5) };
    constexpr bn::sprite_palette_item vancleef(vancleef_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color young_wolf_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(10, 9, 8), bn::color(17, 15, 13), bn::color(22, 19, 16), bn::color(17, 16, 14), bn::color(25, 23, 20), bn::color(29, 5, 3), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(15, 10, 6), bn::color(9, 6, 3), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(9, 9, 9), bn::color(15, 15, 16) };
    constexpr bn::sprite_palette_item young_wolf(young_wolf_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color timber_wolf_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(7, 7, 8), bn::color(12, 12, 13), bn::color(15, 15, 16), bn::color(15, 15, 16), bn::color(22, 22, 23), bn::color(31, 25, 8), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(15, 10, 6), bn::color(9, 6, 3), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(9, 9, 9), bn::color(15, 15, 16) };
    constexpr bn::sprite_palette_item timber_wolf(timber_wolf_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color boar_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(9, 6, 4), bn::color(15, 10, 7), bn::color(19, 13, 9), bn::color(17, 11, 11), bn::color(25, 17, 16), bn::color(29, 5, 3), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(15, 10, 6), bn::color(9, 6, 3), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(9, 9, 9), bn::color(15, 15, 16) };
    constexpr bn::sprite_palette_item boar(boar_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color princess_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(14, 9, 9), bn::color(24, 15, 15), bn::color(31, 19, 19), bn::color(20, 15, 14), bn::color(29, 22, 21), bn::color(5, 3, 3), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(15, 10, 6), bn::color(9, 6, 3), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(9, 9, 9), bn::color(15, 15, 16) };
    constexpr bn::sprite_palette_item princess(princess_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color forest_spider_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(5, 4, 5), bn::color(9, 8, 9), bn::color(11, 10, 11), bn::color(15, 4, 3), bn::color(22, 6, 5), bn::color(29, 6, 4), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(15, 10, 6), bn::color(9, 6, 3), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(9, 9, 9), bn::color(15, 15, 16) };
    constexpr bn::sprite_palette_item forest_spider(forest_spider_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color kobold_vermin_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(11, 8, 4), bn::color(19, 13, 8), bn::color(25, 20, 14), bn::color(9, 6, 4), bn::color(14, 9, 6), bn::color(31, 26, 8), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(15, 10, 6), bn::color(9, 6, 3), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(9, 9, 9), bn::color(15, 15, 16) };
    constexpr bn::sprite_palette_item kobold_vermin(kobold_vermin_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color kobold_tunneler_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(9, 7, 6), bn::color(16, 12, 10), bn::color(23, 19, 15), bn::color(7, 7, 9), bn::color(11, 11, 13), bn::color(31, 26, 8), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(29, 28, 25), bn::color(17, 16, 15), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(9, 9, 9), bn::color(15, 15, 16) };
    constexpr bn::sprite_palette_item kobold_tunneler(kobold_tunneler_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color murloc_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(5, 11, 7), bn::color(9, 19, 12), bn::color(11, 24, 15), bn::color(16, 18, 13), bn::color(23, 26, 19), bn::color(3, 3, 3), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(27, 13, 7), bn::color(16, 7, 4), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(9, 9, 9), bn::color(15, 15, 16) };
    constexpr bn::sprite_palette_item murloc(murloc_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color riverpaw_gnoll_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(14, 11, 6), bn::color(23, 18, 10), bn::color(29, 23, 13), bn::color(10, 6, 3), bn::color(15, 9, 5), bn::color(29, 6, 4), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(15, 10, 6), bn::color(9, 6, 3), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(10, 7, 4), bn::color(17, 12, 7) };
    constexpr bn::sprite_palette_item riverpaw_gnoll(riverpaw_gnoll_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color hogger_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(8, 7, 6), bn::color(14, 12, 11), bn::color(18, 15, 14), bn::color(5, 4, 3), bn::color(8, 6, 5), bn::color(31, 8, 4), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(19, 6, 5), bn::color(11, 3, 3), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(11, 11, 12), bn::color(19, 19, 20) };
    constexpr bn::sprite_palette_item hogger(hogger_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color gnoll_brute_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(11, 10, 8), bn::color(19, 17, 13), bn::color(24, 22, 16), bn::color(7, 6, 4), bn::color(11, 9, 7), bn::color(29, 6, 4), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(11, 11, 13), bn::color(6, 6, 7), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(11, 11, 12), bn::color(19, 19, 20) };
    constexpr bn::sprite_palette_item gnoll_brute(gnoll_brute_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color harvest_watcher_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(10, 7, 4), bn::color(17, 12, 7), bn::color(29, 25, 12), bn::color(17, 15, 10), bn::color(25, 22, 15), bn::color(31, 27, 8), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(12, 15, 8), bn::color(7, 9, 4), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(9, 9, 9), bn::color(15, 15, 16) };
    constexpr bn::sprite_palette_item harvest_watcher(harvest_watcher_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color goblin_engineer_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(8, 13, 5), bn::color(13, 21, 9), bn::color(16, 27, 11), bn::color(10, 7, 5), bn::color(15, 11, 8), bn::color(3, 3, 3), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(25, 22, 9), bn::color(15, 13, 5), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(12, 12, 12), bn::color(20, 20, 21) };
    constexpr bn::sprite_palette_item goblin_engineer(goblin_engineer_colors, bn::bpp_mode::BPP_4);

    constexpr bn::color sneed_colors[] = { bn::color(31, 0, 31), bn::color(3, 2, 3), bn::color(6, 11, 4), bn::color(11, 19, 8), bn::color(14, 24, 10), bn::color(13, 4, 3), bn::color(19, 6, 5), bn::color(3, 3, 3), bn::color(21, 20, 18), bn::color(30, 29, 27), bn::color(29, 23, 8), bn::color(17, 13, 4), bn::color(31, 28, 12), bn::color(29, 16, 5), bn::color(13, 13, 14), bn::color(23, 23, 24) };
    constexpr bn::sprite_palette_item sneed(sneed_colors, bn::bpp_mode::BPP_4);

}

#endif
