#ifndef GW_QUEST_IDS_H
#define GW_QUEST_IDS_H

#include <cstdint>

namespace gw
{

// Keep in the same order as the table in gw_quests.cpp. Saves index quest progress by these values:
// only append, and keep COUNT within gw::max_quests.
enum class quest_id : uint16_t
{
    NONE,
    // Northshire
    A_THREAT_WITHIN,
    KOBOLD_CAMP_CLEANUP,
    WOLVES_ACROSS_THE_BORDER,
    MILLYS_HARVEST,
    BROTHERHOOD_OF_THIEVES,
    REPORT_TO_GOLDSHIRE,
    // Elwynn Forest
    THE_FARGODEEP_MINE,
    GOLD_DUST_EXCHANGE,
    BOUNTY_ON_MURLOCS,
    PROTECT_THE_FRONTIER,
    BOAR_MEAT,
    PRINCESS_MUST_DIE,
    THE_RIVERPAW_THREAT,
    WANTED_HOGGER,
    REPORT_TO_GRYAN,
    // Westfall
    THE_PEOPLES_MILITIA,
    THE_HARVEST_WATCHERS,
    RED_LEATHER_BANDANAS,
    RIVERPAW_GNOLL_BOUNTY,
    THE_DEFIAS_BROTHERHOOD,
    // The Deadmines
    RED_SILK_BANDANAS,
    SNEEDS_SHREDDER,
    EDWIN_VANCLEEF,
    // Stormwind
    THE_ROAD_TO_STORMWIND,
    AN_AUDIENCE_WITH_THE_HIGHLORD,
    LOST_TREASURES,
    // The Stockade
    THE_UNSENT_LETTER,
    THE_STOCKADE_RIOTS,
    BAZIL_THREDD,
    // Beast Mastery
    TAMING_THE_BEAST,
    // Redridge Mountains
    LAKESHIRE_NEEDS_AID,
    ENCROACHING_GNOLLS,
    MURLOC_POACHERS,
    THE_FISHING_CONTEST,
    SOLOMONS_LAW,
    BLACKROCK_MENACE,
    REDRIDGE_GOULASH,
    THE_EVERSTILL_BRIDGE,
    BELLYGRUB,
    BLACKROCK_BOUNTY,
    STONEWATCH_KEEP,
    WANTED_GATH_ILZOGG,
    RETURN_TO_SENTINEL_HILL,
    // Duskwood
    THE_ROAD_TO_DARKSHIRE,
    WOLVES_AT_OUR_HEELS,
    THE_NIGHT_WATCH,
    WORGEN_IN_THE_WOODS,
    THE_LEGEND_OF_STALVAN,
    STALVAN_MISTMANTLE,
    THE_NIGHT_WATCH_II,
    MORBENTS_BANE,
    MORBENT_FEL,
    OGRES_OF_VULGOL,
    THE_HERMITS_ERRAND,
    STITCHES,
    MOR_LADIM,
    // Shadowfang Keep
    INTO_SHADOWFANG,
    THE_BUTCHERS_OF_SHADOWFANG,
    THE_FALLEN_GUARD,
    ARUGAL_MUST_DIE,
    // Ironforge and the Wetlands
    THE_ROAD_TO_IRONFORGE,
    MENETHIL_BOUND,
    THE_THANDOL_SPAN,
    BALGARAS_THE_FOUL,
    YOUNG_CROCOLISK_SKINS,
    ORMERS_REVENGE,
    ORMERS_REVENGE_II,
    DIGGING_UP_THE_PAST,
    WAR_BANNERS,
    DEFEAT_NEK_ROSH,
    // Blackfathom Deeps
    PASSAGE_TO_AUBERDINE,
    IN_SEARCH_OF_THAELRID,
    KNOWLEDGE_IN_THE_DEEPS,
    TWILIGHT_FALLS,
    BEASTS_OF_THE_DEEPS,
    BLACKFATHOM_VILLAINY,
    THE_FATHOM_CORE,
    // Gnomeregan
    THE_GNOMES_PLEA,
    GNOGAINE,
    THE_TROGGS_BELOW,
    GYRODRILLMATIC_EXCAVATIONATORS,
    THE_GRAND_BETRAYAL,
    // Hillsbrad Foothills and the Scarlet Monastery
    THE_ROAD_TO_SOUTHSHORE,
    DOWN_THE_COAST,
    COSTLY_MENACE,
    HINTS_OF_A_NEW_PLAGUE,
    HINTS_OF_A_NEW_PLAGUE_II,
    SYNDICATE_ASSASSINS,
    CRUSHRIDGE_BOUNTY,
    DURNHOLDE_KEEP,
    SYNDICATE_LEADER,
    YETI_HIDES,
    BLOODFANG,
    DOWN_THE_SCARLET_PATH,
    THE_RESTLESS_DEAD,
    TORMENT_IN_THE_GRAVEYARD,
    REST_FOR_IRONSPINE,
    HEARTS_OF_ZEAL,
    MYTHOLOGY_OF_THE_TITANS,
    ARCANIST_DOAN,
    // Stranglethorn Vale and the Scarlet Monastery's Armory and Cathedral
    THE_ROAD_TO_STRANGLETHORN,
    WELCOME_TO_THE_JUNGLE,
    TROLLBANE,
    TIGER_MASTERY,
    BLOODSCALP_HEADHUNTERS,
    PANTHER_MASTERY,
    PASSAGE_TO_BOOTY_BAY,
    RAPTOR_MASTERY,
    BLOODSAIL_BUCCANEERS,
    THE_GREEN_HILLS_OF_STRANGLETHORN,
    RAPTOR_MASTERY_II,
    GORILLA_FANGS,
    THE_BLOODSAIL_SEA_DOGS,
    FLEET_MASTER_FIRALLON,
    BIG_GAME_HUNTER,
    ARMS_OF_THE_CRUSADE,
    HERODS_FALL,
    THE_CRIMSON_CATHEDRAL,
    IN_THE_NAME_OF_THE_LIGHT,
    // Tanaris, Thousand Needles, Razorfen Kraul, Razorfen Downs and Zul'Farrak
    STEAMWHEEDLE_BUSINESS,
    WASTEWANDER_JUSTICE,
    WATER_POUCH_BOUNTY,
    CALIPH_SCORPIDSTING,
    SOUTHSEA_SHAKEDOWN,
    ANDRE_FIREBEARD,
    DUNEMAUL_COMPOUND,
    SANDSORROW_WATCH,
    TROLL_TEMPER,
    SCARAB_SHELLS,
    GAHZ_RILLA,
    CHIEF_UKORZ_SANDSCALP,
    THE_MIRAGE_RACEWAY,
    GALAK_RAIDERS,
    SALTSTONE_BASILISKS,
    INTO_THE_KRAUL,
    THE_CRONE_OF_THE_KRAUL,
    DOWNS_OF_THE_DEAD,
    THE_GONG_OF_THE_DOWNS,
    BRING_THE_LIGHT,
    COUNT
};

}

#endif
