#include "gw_npc_data.h"

#include "gw_abilities.h"

namespace gw
{

namespace
{
    using l = look_id;
    using c = class_id;

    constexpr uint8_t vendor = npc_flag::VENDOR;
    constexpr uint8_t trainer = npc_flag::TRAINER;
    constexpr uint8_t innkeeper = npc_flag::INNKEEPER | npc_flag::VENDOR;
    constexpr uint8_t flight_master = npc_flag::FLIGHT_MASTER;

    // Vendor stock lists, see gw_vendors.
    constexpr uint8_t general_goods = 0;
    constexpr uint8_t weapons = 1;
    constexpr uint8_t armor = 2;
    constexpr uint8_t inn = 3;
    constexpr uint8_t militia = 4;
    constexpr uint8_t stormwind_goods = 5;
    constexpr uint8_t stormwind_weapons = 6;
    constexpr uint8_t stormwind_armor = 7;
    constexpr uint8_t lakeshire = 8;
    constexpr uint8_t darkshire = 9;
    constexpr uint8_t ironforge_goods = 10;
    constexpr uint8_t ironforge_smith = 11;
    constexpr uint8_t menethil = 12;
    constexpr uint8_t southshore = 13;
    constexpr uint8_t southshore_smith = 14;
    constexpr uint8_t jungle_goods = 15;
    constexpr uint8_t booty_bay_smith = 16;
    constexpr uint8_t gadgetzan_goods = 17;
    constexpr uint8_t gadgetzan_smith = 18;
    constexpr uint8_t feathermoon_goods = 19;
    constexpr uint8_t feathermoon_smith = 20;
    constexpr uint8_t vigil_goods = 21;
    constexpr uint8_t vigil_smith = 22;
    constexpr uint8_t thorium_brotherhood = 23;
    constexpr uint8_t grim_guzzler = 24;

    constexpr npc_info npcs[] = {
        { "", "", l::PEASANT, 0, c::WARRIOR, 0, "" },
        { "Deputy Willem", "", l::GUARD, 0, c::WARRIOR, 0,
          "Stay alert, citizen. The Defias grow bolder every day." },
        { "Marshal McBride", "", l::MARSHAL, 0, c::WARRIOR, 0,
          "The Light watches over Northshire, but it needs strong arms too." },
        { "Llane Beshere", "Warrior Trainer", l::TRAINER_WARRIOR, trainer, c::WARRIOR, 0,
          "Steel and rage, friend. Let me teach you to use both." },
        { "Brother Danil", "General Supplies", l::PRIEST, vendor, c::WARRIOR, general_goods,
          "Welcome, child. Rest a while and take what you need." },
        { "Northshire Guard", "", l::GUARD, 0, c::WARRIOR, 0,
          "The road south leads to Goldshire. Keep your blade ready." },
        { "Marshal Dughan", "", l::MARSHAL, 0, c::WARRIOR, 0,
          "Goldshire is under my protection. Gnolls and kobolds test that every day." },
        { "Lyria Du Lac", "Warrior Trainer", l::TRAINER_WARRIOR_F, trainer, c::WARRIOR, 0,
          "A warrior is never done learning. What do you need?" },
        { "Corina Steele", "Weaponsmith", l::SMITH, vendor, c::WARRIOR, weapons,
          "Finest blades this side of Stormwind. Have a look." },
        { "Innkeeper Farley", "Innkeeper", l::INNKEEPER, innkeeper, c::WARRIOR, inn,
          "Welcome to the Lion's Pride! Something to eat or drink?" },
        { "Remy \"Two Times\"", "", l::MERCHANT, 0, c::WARRIOR, 0,
          "Two times the gold, two times the fun. That's my motto." },
        { "Guard Thomas", "", l::GUARD, 0, c::WARRIOR, 0,
          "Wolves and spiders keep creeping out of the woods." },
        { "Deputy Rainer", "", l::GUARD, 0, c::WARRIOR, 0,
          "West of here lies Westfall. Gnolls lurk in the woods to the south." },
        { "Ma Stonefield", "", l::FARMER_F, 0, c::WARRIOR, 0,
          "Pa's out in the fields. Mind the boars, they're ornery this year." },
        { "Gryan Stoutmantle", "People's Militia", l::MILITIA, 0, c::WARRIOR, 0,
          "Stormwind abandoned Westfall. Only the militia stands against the Defias." },
        { "Salma Saldean", "", l::FARMER_F2, 0, c::WARRIOR, 0,
          "Our farm was overrun by those metal scarecrows. What a mess." },
        { "Scout Galiaan", "People's Militia", l::MILITIA, 0, c::WARRIOR, 0,
          "I scout the roads for the militia. There are Defias everywhere." },
        { "Khelden Bremen", "Mage Trainer", l::MAGE_TRAINER, trainer, c::MAGE, 0,
          "Magic is a discipline, not a toy. Are you ready to learn?" },
        { "Thorgas Grimson", "Hunter Trainer", l::HUNTER_TRAINER, trainer, c::HUNTER, 0,
          "A steady hand and a keen eye. That's all a hunter needs." },
        { "Eagan Peltskinner", "", l::PEASANT, 0, c::WARRIOR, 0,
          "Wolves keep coming over the ridge, and I'm short on meat." },
        { "Milly Osworth", "", l::FARMER_F2, 0, c::WARRIOR, 0,
          "The vineyard was my family's pride, until the Defias came." },
        { "Andrew Krighton", "Armorer", l::SMITH, vendor, c::WARRIOR, armor,
          "Armor for the road ahead. Cloth, leather, mail, all at fair prices." },
        { "Farmer Furlbrow", "", l::PEASANT, 0, c::WARRIOR, 0,
          "The Defias took our farm, and now gnolls roam the fields." },
        { "Quartermaster Lewis", "Militia Supplies", l::MERCHANT, vendor, c::WARRIOR, militia,
          "The militia needs supplies, and so will you. Take a look." },
        { "Innkeeper Heather", "Innkeeper", l::INNKEEPER, innkeeper, c::WARRIOR, inn,
          "No roof yet, but a warm fire and a hot meal. Rest here as long as you like." },
        { "General Marcus Jonathan", "", l::MARSHAL, 0, c::WARRIOR, 0,
          "Welcome to Stormwind, the jewel of the Alliance. Keep the peace inside these walls." },
        { "Stormwind City Guard", "", l::STORMWIND_GUARD, 0, c::WARRIOR, 0,
          "The keep is to the north-west, the Trade District straight ahead over the canal." },
        { "Royal Guard", "", l::STORMWIND_GUARD, 0, c::WARRIOR, 0,
          "Highlord Bolvar speaks for the throne while the king is away. Show respect." },
        { "Stormwind City Guard", "", l::STORMWIND_GUARD, 0, c::WARRIOR, 0,
          "Inn to the west, smiths to the east. The mages keep to their quarter, south of the canal." },
        { "Highlord Bolvar Fordragon", "", l::BOLVAR, 0, c::WARRIOR, 0,
          "Stormwind stands because people like you defend its lands. The Light be with you." },
        { "Archbishop Benedictus", "", l::ARCHBISHOP, 0, c::WARRIOR, 0,
          "The Cathedral of Light is open to all who seek comfort. May the Light guide your path." },
        { "Innkeeper Allison", "Innkeeper", l::INNKEEPER_F, innkeeper, c::WARRIOR, stormwind_goods,
          "Welcome to the Gilded Rose, the finest inn in the city." },
        { "Gunther Weller", "Weaponsmith", l::SMITH, vendor, c::WARRIOR, stormwind_weapons,
          "Steel from the Dwarven District. None better this side of Ironforge." },
        { "Lina Stover", "Armorer", l::MERCHANT, vendor, c::WARRIOR, stormwind_armor,
          "Ringmail, studded leather, padded cloth. Whatever you fight in, I have it." },
        { "Thurman Mullby", "General Goods", l::PEASANT, vendor, c::WARRIOR, stormwind_goods,
          "Supplies for the road! Food, drink and potions, fresh every morning." },
        { "Jennea Cannon", "Mage Trainer", l::MAGE_TRAINER, trainer, c::MAGE, 0,
          "The Mage Quarter welcomes serious students. Have you come to learn?" },
        { "Einris Brightspear", "Hunter Trainer", l::HUNTER_TRAINER, trainer, c::HUNTER, 0,
          "The wilds are your true teacher. I only sharpen what you learn there." },
        { "Brann Bronzebeard", "Explorers' League", l::EXPLORER, 0, c::WARRIOR, 0,
          "Old mines, lost ruins, buried treasure! The world is full of secrets, lad." },
        { "Ander Germaine", "Warrior Trainer", l::TRAINER_WARRIOR, trainer, c::WARRIOR, 0,
          "Old Town breeds tough fighters. Let's see if you have what it takes." },
        { "Warden Thelwater", "The Stockade", l::WARDEN, 0, c::WARRIOR, 0,
          "The prisoners rose this morning and took the cells. Go in armed." },
        { "Stormwind City Guard", "", l::STORMWIND_GUARD, 0, c::WARRIOR, 0,
          "That's the Stockade. Riot or no riot, whatever comes out of that gate doesn't get past me." },
        { "Dungar Longdrink", "Gryphon Master", l::GRYPHON_MASTER, flight_master, c::WARRIOR, 0,
          "My gryphons fly to every flight master you've met." },
        { "Thor", "Gryphon Master", l::GRYPHON_MASTER, flight_master, c::WARRIOR, 0,
          "Sentinel Hill's gryphons are saddled. Where to?" },
        { "Randal Hunter", "Riding Trainer", l::RIDING_TRAINER, trainer, any_class, 0,
          "Reach level 30, bring 5 gold, and I'll teach you to ride." },
        { "Monty", "Deeprun Tram", l::TRAM_CONDUCTOR, 0, c::WARRIOR, 0,
          "Those stairs lead up to Ironforge. The tram goes back any time." },
        { "Magistrate Solomon", "", l::MAGISTRATE, 0, c::WARRIOR, 0,
          "Lakeshire stands alone. Stormwind sends letters, not soldiers." },
        { "Marshal Marris", "", l::MARSHAL, 0, c::WARRIOR, 0,
          "The Blackrock orcs come down from the keep every night. We need every blade." },
        { "Foreman Oslow", "", l::FOREMAN, 0, c::WARRIOR, 0,
          "That bridge won't fix itself, and my crew won't go near the orcs." },
        { "Dockmaster Baren", "", l::DOCKMASTER, 0, c::WARRIOR, 0,
          "Murlocs in the lake, gnolls on the shore. Fine place to run a dock." },
        { "Chef Breanna", "", l::CHEF_F, 0, c::WARRIOR, 0,
          "Nobody leaves the Lakeshire Inn hungry. Not while I'm cooking." },
        { "Innkeeper Brianna", "Innkeeper", l::INNKEEPER_F, innkeeper, c::WARRIOR, lakeshire,
          "Welcome to the Lakeshire Inn. Warm beds and a view of the lake." },
        { "Verner Osgood", "", l::PEASANT, 0, c::WARRIOR, 0,
          "There's a boar in the hills as big as a cart. Bellygrub, they call it." },
        { "Bray the Fisherman", "", l::FISHERMAN, 0, c::WARRIOR, 0,
          "Face the lake from the shore and press A to cast. Patience does the rest." },
        { "Guard Berton", "", l::GUARD, 0, c::WARRIOR, 0,
          "The gnolls in the west hills grow bolder. Keep your eyes open." },
        { "Ariena Stormfeather", "Gryphon Master", l::GRYPHON_MASTER_F, flight_master, c::WARRIOR, 0,
          "Lakeshire's gryphons fly to Stormwind and beyond." },
        { "Karen Taylor", "General Goods", l::MERCHANT, vendor, c::WARRIOR, lakeshire,
          "Food, drink and potions for the road. The orcs won't sell you any." },
        { "Lakeridge Guard", "", l::GUARD, 0, c::WARRIOR, 0,
          "This road runs south to Duskwood. It's always night down there. Keep to the road." },
        // Duskwood
        { "Lord Ello Ebonlocke", "Darkshire", l::ELLO_EBONLOCKE, 0, c::WARRIOR, 0,
          "Darkshire hasn't seen the sun in years. We learned to fight in the dark." },
        { "Commander Althea", "The Night Watch", l::ALTHEA_EBONLOCKE, 0, c::WARRIOR, 0,
          "The Night Watch holds the gate. Every night the dead come a little closer." },
        { "Madame Eva", "Fortune Teller", l::MADAME_EVA, 0, c::WARRIOR, 0,
          "The cards speak of a mist, a ring and a broken heart. Sit, child. Listen." },
        { "Sirra Von'Indi", "Scholar", l::SIRRA_VON_INDI, 0, c::WARRIOR, 0,
          "The undead of Duskwood answer to someone. I mean to find out who." },
        { "Calor", "Weaponsmith", l::CALOR, vendor, c::WARRIOR, stormwind_weapons,
          "Silver would be better against the worgen. Steel will have to do." },
        { "Innkeeper Trelayne", "Innkeeper", l::TRELAYNE, innkeeper, c::WARRIOR, darkshire,
          "The Scarlet Raven Tavern. Light, warmth and a locked door." },
        { "Felicia Maline", "Gryphon Master", l::FELICIA_MALINE, flight_master, c::WARRIOR, 0,
          "My gryphons fly north to Silverpine, where the worgen first came from." },
        { "Night Watch Guard", "", l::NIGHT_WATCH, 0, c::WARRIOR, 0,
          "Something big walks the road from Raven Hill some nights. We hear it before we see it." },
        { "Night Watch Guard", "", l::NIGHT_WATCH, 0, c::WARRIOR, 0,
          "Stay near the lamps. Whatever is out there doesn't like the light." },
        { "Viktori Prism'Antras", "General Goods", l::MERCHANT, vendor, c::WARRIOR, darkshire,
          "Candles, bread, bandages. Darkshire runs on all three." },
        { "Sven Yorgen", "", l::SVEN_YORGEN, 0, c::WARRIOR, 0,
          "Raven Hill was my home. Now the dead live there, and I live in a tent." },
        { "Abercrombie", "", l::ABERCROMBIE, 0, c::WARRIOR, 0,
          "Go away! Can't an old man work in peace? Don't touch anything in the shed." },
        // Silverpine Forest
        { "Ranger Valdan", "Alliance Scout", l::RANGER_VALDAN, 0, c::WARRIOR, 0,
          "Arugal's worgen pour out of Shadowfang every night. Somebody has to go in." },
        { "Gryphon Rider Hask", "Gryphon Master", l::GRYPHON_MASTER, flight_master, c::WARRIOR, 0,
          "One gryphon, one rider, and the fastest way out of this forest." },
        // Ironforge
        { "King Magni Bronzebeard", "Lord of Ironforge", l::MAGNI_BRONZEBEARD, 0, c::WARRIOR, 0,
          "Welcome to Ironforge, friend. Bolvar's champions are welcome here." },
        { "Royal Guard", "", l::IRONFORGE_GUARD, 0, c::WARRIOR, 0,
          "The king's busy. Unless you've come about the Wetlands. Then he's not." },
        { "Gerrig Bonegrip", "Explorers' League", l::DWARF_MERCHANT, 0, c::WARRIOR, 0,
          "Old ruins, old books, old secrets. The deeper you dig, the more you find." },
        { "Ironforge Guard", "", l::IRONFORGE_GUARD, 0, c::WARRIOR, 0,
          "Mind the Great Forge, it's hotter than it looks. And it looks hot." },
        { "Gryth Thurden", "Gryphon Master", l::GRYPHON_MASTER, flight_master, c::WARRIOR, 0,
          "My gryphons know every peak between here and Stormwind." },
        { "Innkeeper Firebrew", "Innkeeper", l::DWARF_INNKEEPER, innkeeper, c::WARRIOR, ironforge_goods,
          "The Stonefire Tavern! Best ale under the mountain, and the only ale." },
        { "Kurdrum Barleybeard", "General Goods", l::DWARF_MERCHANT, vendor, c::WARRIOR, ironforge_goods,
          "Cheese, ale, potions: everything a dwarf needs, and more." },
        { "Bruuk Barleybeard", "Smith", l::DWARF_SMITH, vendor, c::WARRIOR, ironforge_smith,
          "Forged at the Great Forge. No better steel this side of Grim Batol." },
        { "High Tinker Mekkatorque", "King of Gnomes", l::MEKKATORQUE, 0, c::WARRIOR, 0,
          "Gnomeregan was the jewel of gnomish engineering. One day it will be again!" },
        { "Shoni the Shilent", "Tinker", l::TINKER_GNOME, 0, c::WARRIOR, 0,
          "..." },
        { "Kelstrum Stonebreaker", "Warrior Trainer", l::DWARF_WARRIOR, trainer, c::WARRIOR, 0,
          "Hit hard, hit first, keep your shield up. That's most of the training." },
        { "Olmin Burningbeard", "Hunter Trainer", l::HUNTER_TRAINER, trainer, c::HUNTER, 0,
          "A good hunter knows the mountain and every beast on it." },
        { "Juli Stormkettle", "Mage Trainer", l::MAGE_TRAINER, trainer, c::MAGE, 0,
          "Magic in Ironforge? We're not all hammers and ale, you know." },
        // Dun Morogh
        { "Ironforge Guard", "", l::IRONFORGE_GUARD, 0, c::WARRIOR, 0,
          "Ironforge's gate has never fallen. Gnomeregan is west, the Wetlands are through the pass east." },
        { "Ozzie Togglevolt", "Tinker", l::OZZIE_TOGGLEVOLT, 0, c::WARRIOR, 0,
          "We flooded Gnomeregan to drive out the troggs. It didn't quite go to plan." },
        { "Mountaineer Kadrell", "", l::IRONFORGE_GUARD, 0, c::WARRIOR, 0,
          "The gnomes camp here since their city fell. I keep the troggs off them." },
        // Wetlands
        { "Captain Stoutfist", "Menethil Harbor", l::CAPTAIN_STOUTFIST, 0, c::WARRIOR, 0,
          "Menethil holds the road north. The Dark Irons and the orcs both want it." },
        { "Innkeeper Helbrek", "Innkeeper", l::DWARF_INNKEEPER, innkeeper, c::WARRIOR, menethil,
          "The Deepwater Tavern. Dry beds, warm food and the sea outside the window." },
        { "Edwina Monzor", "General Goods", l::MERCHANT, vendor, c::WARRIOR, menethil,
          "Everything the harbor sells, I sell. Except fish. Ask James." },
        { "Shellei Brondir", "Gryphon Master", l::GRYPHON_MASTER_F, flight_master, c::WARRIOR, 0,
          "Ironforge, Stormwind, anywhere you've been. My gryphons don't mind rain." },
        { "James Halloran", "", l::JAMES_HALLORAN, 0, c::WARRIOR, 0,
          "The crocolisks in these bogs grow fast. The young ones have the softest hides." },
        { "Harbormaster Foggywater", "Harbormaster", l::DOCKMASTER, 0, c::WARRIOR, 0,
          "The boat to Auberdine leaves from the long pier. Kalimdor's over the sea." },
        { "Menethil Guard", "", l::MENETHIL_GUARD, 0, c::WARRIOR, 0,
          "Watch the bogs east of town. The crocolisks take a leg as soon as look at you." },
        { "Prospector Whelgar", "Explorers' League", l::PROSPECTOR_WHELGAR, 0, c::WARRIOR, 0,
          "Years of digging, and the gnolls walk off with the finds in an afternoon." },
        { "Ormer Ironbraid", "", l::ORMER_IRONBRAID, 0, c::WARRIOR, 0,
          "The raptors on the ridge took my brother. I've been hunting them ever since." },
        // Darkshore
        { "Innkeeper Shaussiy", "Innkeeper", l::NIGHT_ELF_INNKEEPER, innkeeper, c::WARRIOR, menethil,
          "Rest, traveler. Auberdine's nights are long and quiet." },
        { "Dawnwatcher Shaedlass", "", l::DAWNWATCHER_SHAEDLASS, 0, c::WARRIOR, 0,
          "Something stirs in Blackfathom Deeps, south along the coast. The Twilight's Hammer, I fear." },
        { "Caylais Moonfeather", "Hippogryph Master", l::HIPPOGRYPH_MASTER, flight_master, c::WARRIOR, 0,
          "My hippogryphs fly only over Kalimdor. For the east, take the boat." },
        { "Sentinel Glynda", "", l::SENTINEL, 0, c::WARRIOR, 0,
          "The naga swarm on the Zoram Strand. Keep your blade ready if you walk south." },
        // Blackfathom Deeps
        { "Argent Guard Thaelrid", "The Argent Dawn", l::ARGENT_GUARD_THAELRID, 0, c::WARRIOR, 0,
          "The Twilight's Hammer serve something old in these waters: Aku'mai." },
        // Southshore
        { "Magistrate Henry Maleb", "", l::MAGISTRATE_MALEB, 0, c::WARRIOR, 0,
          "Southshore holds, but only just. The Syndicate and the Forsaken both want these hills." },
        { "Marshal Redpath", "", l::MARSHAL, 0, c::WARRIOR, 0,
          "Ogres in the north, thieves in Strahnbrad, and my men stretched thin as parchment." },
        { "Raleigh the Devout", "", l::RALEIGH_THE_DEVOUT, 0, c::WARRIOR, 0,
          "The Light shelters Southshore. The Scarlet Crusade claims it shelters them too." },
        { "Loremaster Dibbs", "", l::LOREMASTER_DIBBS, 0, c::WARRIOR, 0,
          "The Scarlet library holds tales of the titans older than Ironforge itself." },
        { "Darren Malvew", "", l::DARREN_MALVEW, 0, c::WARRIOR, 0,
          "Lions and yetis both raid my stock. I pay well for every pelt you bring." },
        { "Innkeeper Anderson", "Innkeeper", l::SOUTHSHORE_INNKEEPER, innkeeper, c::WARRIOR, southshore,
          "Welcome to the Southshore inn. Fresh fish, warm beds, no questions." },
        { "Sarah Raycroft", "General Goods", l::MERCHANT, vendor, c::WARRIOR, southshore,
          "Supplies for the road north. You'll want them in the Alterac foothills." },
        { "Robert Aebischer", "Blacksmith", l::SMITH, vendor, c::WARRIOR, southshore_smith,
          "Southshore steel. Not as pretty as Ironforge's, but it'll stop an ogre club." },
        { "Darla Harris", "Gryphon Master", l::GRYPHON_MASTER_F, flight_master, c::WARRIOR, 0,
          "My gryphons fly as far as the glades of Tirisfal." },
        { "Southshore Guard", "", l::GUARD, 0, c::WARRIOR, 0,
          "Keep clear of Durnholde. The Syndicate hold the old keep now." },
        // Tirisfal Glades
        { "Argent Scout Nathan", "The Argent Dawn", l::ARGENT_SCOUT, 0, c::WARRIOR, 0,
          "The Scarlet Crusade guard their monastery like a fortress. Zeal gone sour." },
        { "Gryphon Rider Talan", "Gryphon Master", l::GRYPHON_MASTER, flight_master, c::WARRIOR, 0,
          "Argent Watch is no town, but my gryphons will carry you south to Southshore." },
        // Stranglethorn Vale
        { "Lieutenant Doren", "", l::LIEUTENANT_DOREN, 0, c::WARRIOR, 0,
          "Stormwind forgot us out here. The jungle didn't, and neither did the trolls." },
        { "Corporal Bluth", "Camp Trader", l::CORPORAL_BLUTH, vendor, c::WARRIOR, jungle_goods,
          "Supplies are thin out here, but what I have is yours. For a price." },
        { "Rebel Soldier", "", l::REBEL_SOLDIER, 0, c::WARRIOR, 0,
          "Keep your blade close. The Bloodscalps collect heads." },
        { "Hemet Nesingwary", "", l::HEMET_NESINGWARY, 0, c::WARRIOR, 0,
          "The finest hunting in the world, right here in this jungle. Mind the tigers." },
        { "Ajeck Rouack", "", l::AJECK_ROUACK, 0, c::WARRIOR, 0,
          "Tigers first. Then we can talk about the real game." },
        { "Sir S. J. Erlgadin", "", l::SIR_S_J_ERLGADIN, 0, c::WARRIOR, 0,
          "A gentleman hunts with patience. The panthers test it sorely." },
        { "Barnil Stonepot", "", l::BARNIL_STONEPOT, 0, c::WARRIOR, 0,
          "Hemet's book is the finest ever written. If only I had every page." },
        { "Baron Revilgaz", "", l::BARON_REVILGAZ, 0, c::WARRIOR, 0,
          "Booty Bay is neutral, friend. Neutral, and very profitable." },
        { "Fleet Master Seahorn", "", l::FLEET_MASTER_SEAHORN, 0, c::WARRIOR, 0,
          "The Bloodsail want my port. They'll get my cannons first." },
        { "Kebok", "", l::KEBOK, 0, c::WARRIOR, 0,
          "Got a job for you. Pays good. Don't ask who it's for." },
        { "Innkeeper Skindle", "Innkeeper", l::INNKEEPER_SKINDLE, innkeeper, c::WARRIOR, jungle_goods,
          "Rooms by the sea, rum by the barrel. Coin up front." },
        { "Gyll", "Gryphon Master", l::GYLL, flight_master, c::WARRIOR, 0,
          "My gryphons fly north to Darkshire and beyond." },
        { "Booty Bay Bruiser", "", l::BOOTY_BAY_BRUISER, 0, c::WARRIOR, 0,
          "No fighting in the bay. Take it outside the tunnel, pal." },
        { "Drizzlik", "General Goods", l::BOOTY_BAY_VENDOR, vendor, c::WARRIOR, jungle_goods,
          "Fruit, rum and bandages. All the jungle asks of you." },
        { "Brikk Keencraft", "Blacksmith", l::BOOTY_BAY_SMITH, vendor, c::WARRIOR, booty_bay_smith,
          "Goblin steel, the sharpest in the south. Guaranteed. Mostly." },
        // Tanaris
        { "Engineer Bilgewhizzle", "", l::BILGEWHIZZLE, 0, c::WARRIOR, 0,
          "Gadgetzan runs on water and coin. The bandits steal the one and owe us the other." },
        { "Innkeeper Fizzgrimble", "Innkeeper", l::INNKEEPER_FIZZGRIMBLE, innkeeper, c::WARRIOR, gadgetzan_goods,
          "Cold water, warm beds. The sand gets in either way." },
        { "Blizrik Buckshot", "General Goods", l::BLIZRIK_BUCKSHOT, vendor, c::WARRIOR, gadgetzan_goods,
          "Quail, desert water and potions. The desert takes the rest." },
        { "Krinkle Goodsteel", "Blacksmith", l::KRINKLE_GOODSTEEL, vendor, c::WARRIOR, gadgetzan_smith,
          "Goodsteel by name, good steel by trade. Have a look." },
        { "Trenton Lighthammer", "", l::TRENTON_LIGHTHAMMER, 0, c::WARRIOR, 0,
          "The Dunemaul ogres raid our caravans from their compound in the south." },
        { "Fizzledowser", "", l::FIZZLEDOWSER, 0, c::WARRIOR, 0,
          "There's water under all this sand. Getting it out before the bandits do is the trick." },
        { "Tran'rek", "", l::TRANREK, 0, c::WARRIOR, 0,
          "The Sandfury trolls of Zul'Farrak watch the west. Their city is older than the sand." },
        { "Bera Stonehammer", "Gryphon Master", l::BERA_STONEHAMMER, flight_master, c::WARRIOR, 0,
          "First roost in Kalimdor. More to come." },
        { "Gadgetzan Bruiser", "", l::GADGETZAN_BRUISER, 0, c::WARRIOR, 0,
          "No brawling in Gadgetzan. Take it out to the dunes, pal." },
        { "Stoley", "", l::STOLEY, 0, c::WARRIOR, 0,
          "Southsea pirates squat at Lost Rigger Cove. Bad for business, worse for the port." },
        // Thousand Needles
        { "Pozzik", "", l::POZZIK, 0, c::WARRIOR, 0,
          "The Mirage Raceway! Fastest track in Kalimdor, when the engines hold together." },
        { "Kravel Koalbeard", "", l::KRAVEL_KOALBEARD, 0, c::WARRIOR, 0,
          "The Galak centaurs raid the track and the basilisks eat the rest. Bad season." },
        { "Fizzle Brassbolts", "", l::FIZZLE_BRASSBOLTS, 0, c::WARRIOR, 0,
          "The quilboar nest in thorns to the north-west. Razorfen Kraul, they call it." },
        { "Wizzle Brassbolts", "", l::WIZZLE_BRASSBOLTS, 0, c::WARRIOR, 0,
          "A hydra in Zul'Farrak's pool! Its scales would make a fine racing engine." },
        { "Argent Guard Dalen", "The Argent Dawn", l::ARGENT_GUARD_DALEN, 0, c::WARRIOR, 0,
          "The Scourge took the Razorfen Downs. Now the quilboar dead walk." },
        // Feralas
        { "Shandris Feathermoon", "General", l::SHANDRIS_FEATHERMOON, 0, c::WARRIOR, 0,
          "Feathermoon stands. The ogres and naga will learn to fear it." },
        { "Latronicus Moonspear", "", l::LATRONICUS_MOONSPEAR, 0, c::WARRIOR, 0,
          "The Hatecrest naga crawl up our shores. I want them back in the sea." },
        { "Angelas Moonbreeze", "", l::FEATHERMOON_RANGER, 0, c::WARRIOR, 0,
          "The wildkin of Feralas have gone mad. Something poisons the Dream Bough." },
        { "Pratt McGrubben", "Leatherworker", l::PRATT_MCGRUBBEN, 0, c::WARRIOR, 0,
          "Yeti hide makes the best leather there is. If you can get it." },
        { "Kindal Moonweaver", "", l::FEATHERMOON_DRUID, 0, c::WARRIOR, 0,
          "The Grimtotem tauren trap the wild things of the forest. I want it stopped." },
        { "Innkeeper Shyria", "Innkeeper", l::NIGHT_ELF_INNKEEPER, innkeeper, c::WARRIOR, feathermoon_goods,
          "Rest here. The sea keeps the ogres off the island." },
        { "Vivianna", "Trade Goods", l::FEATHERMOON_VENDOR, vendor, c::WARRIOR, feathermoon_goods,
          "Everything the boat brings, I sell. Mostly." },
        { "Brannol Eaglemoon", "Blacksmith", l::FEATHERMOON_SMITH, vendor, c::WARRIOR, feathermoon_smith,
          "Moonsteel, forged on the island. Light and true." },
        { "Fyldren Moonfeather", "Hippogryph Master", l::HIPPOGRYPH_MASTER, flight_master, c::WARRIOR, 0,
          "Hold on tight over the sea." },
        { "Feathermoon Sentinel", "", l::SENTINEL, 0, c::WARRIOR, 0,
          "The boat takes you to the Forgotten Coast. Mind the naga." },
        { "Zorbin Fandazzle", "", l::ZORBIN_FANDAZZLE, 0, c::WARRIOR, 0,
          "Shore striders! Giants of the sea, and I'll prove it with science." },
        { "Azj'Tordin", "", l::HIGHBORNE_EXILE, 0, c::WARRIOR, 0,
          "Eldre'Thalas was ours once. Now it is the Dire Maul, and the Felvine grows in it." },
        // Desolace
        { "Captain Talendria", "", l::NIJEL_SENTINEL, 0, c::WARRIOR, 0,
          "Nijel's Point holds, but the centaurs and the satyrs press us hard." },
        { "Marandis", "", l::NIJEL_DRUID, 0, c::WARRIOR, 0,
          "The earth itself is sick here. Its heart lies in Maraudon." },
        { "Willow", "", l::FEATHERMOON_DRUID, 0, c::WARRIOR, 0,
          "Theradras's servants carve her name into crystal. I want to know why." },
        { "Innkeeper Lyshaerya", "Innkeeper", l::NIGHT_ELF_INNKEEPER, innkeeper, c::WARRIOR, feathermoon_goods,
          "A warm bed in a cold land." },
        { "Baritanas Skyriver", "Hippogryph Master", l::HIPPOGRYPH_MASTER, flight_master, c::WARRIOR, 0,
          "Desolace looks better from the sky." },
        { "Cavindra", "", l::FEATHERMOON_DRUID, 0, c::WARRIOR, 0,
          "Maraudon was Zaetar's grave. Now it is a sickness that spreads." },
        // Dire Maul
        { "Shen'dralar Ancient", "", l::SHENDRALAR_ANCIENT, 0, c::WARRIOR, 0,
          "We fed a demon to keep our magic. Now it will eat us all." },
        // The Burning Steppes
        { "Marshal Maxwell", "", l::MARSHAL, 0, c::WARRIOR, 0,
          "Blackrock Mountain looms over us. Orcs, ogres and worse come down every day." },
        { "Oralius", "", l::ORALIUS, 0, c::WARRIOR, 0,
          "The Firegut ogres of Dreadmaul Rock burn everything they can reach." },
        { "Jalinde Summerdrake", "", l::JALINDE_SUMMERDRAKE, 0, c::WARRIOR, 0,
          "Black dragons nest on the Flame Crest. Their master sleeps under the mountain." },
        { "Ragged John", "", l::RAGGED_JOHN, 0, c::WARRIOR, 0,
          "Sit down, friend! Did I ever tell you how I beat a black dragon at drinking?" },
        { "Innkeeper Brianna", "Innkeeper", l::INNKEEPER, innkeeper, c::WARRIOR, vigil_goods,
          "Ash in the beer, ash in the bread. You get used to it." },
        { "Mallory Dunwood", "Trade Goods", l::MERCHANT, vendor, c::WARRIOR, vigil_goods,
          "Supplies come over the pass from Lakeshire. When the orcs let them." },
        { "Haldor Ashforge", "Blacksmith", l::SMITH, vendor, c::WARRIOR, vigil_smith,
          "Thorium steel, forged in the heat of the Steppes. It won't melt on you." },
        { "Borgus Steelhand", "Gryphon Master", l::GRYPHON_MASTER, flight_master, c::WARRIOR, 0,
          "My gryphons hate the smoke. Fly high and fast." },
        // The Searing Gorge and the Badlands
        { "Kalaran Windblade", "", l::KALARAN_WINDBLADE, 0, c::WARRIOR, 0,
          "The Dark Iron work slaves to death in the Cauldron. I mean to stop it." },
        { "Lokhtos Darkbargainer", "The Thorium Brotherhood", l::LOKHTOS_DARKBARGAINER, vendor, c::WARRIOR,
          thorium_brotherhood, "The Brotherhood broke with the emperor. We sell to friends." },
        { "Prospector Ryedol", "Explorers' League", l::EXPLORER, 0, c::WARRIOR, 0,
          "Uldaman! A titan vault under the Badlands, and troggs in it." },
        { "Theldurin the Lost", "", l::THELDURIN_THE_LOST, 0, c::WARRIOR, 0,
          "I lost my brother Agmond in Uldaman. I won't lose the vault as well." },
        // The Swamp of Sorrows
        { "Brohann Caskbelly", "Explorers' League", l::PROSPECTOR_WHELGAR, 0, c::WARRIOR, 0,
          "The Atal'ai sank a temple in the Pool of Tears. They pray in it still." },
        { "Marvon Rivetseeker", "", l::MARVON_RIVETSEEKER, 0, c::WARRIOR, 0,
          "The temple's statues hold a pattern. Light them in the right order, I say." },
        { "Thaena Lightwing", "Gryphon Master", l::GRYPHON_MASTER_F, flight_master, c::WARRIOR, 0,
          "The swamp eats gryphons. Fly straight over it." },
        // Blackrock Depths
        { "Marshal Windsor", "", l::MARSHAL_WINDSOR, 0, c::WARRIOR, 0,
          "They took us at the mountain's gate. Get me out of this cell!" },
        { "Plugger Spazzring", "The Grim Guzzler", l::PLUGGER_SPAZZRING, vendor, c::WARRIOR, grim_guzzler,
          "Drink up, or get out. No fighting in my bar." },
        { "Grim Patron", "", l::GUZZLER_PATRON, 0, c::WARRIOR, 0,
          "Thunderbrew's in the cellar. Don't tell Plugger." },
    };

    static_assert(sizeof(npcs) / sizeof(npcs[0]) == int(npc_id::COUNT));
}

const npc_info& get_npc_info(npc_id npc)
{
    int index = int(npc);
    return npcs[index < int(npc_id::COUNT) ? index : 0];
}

}
